### ISSUE TITLE
Build Feeds fail while compiling kernel-module-extrawlan-rtl8189es OV 10.1-r164 for DM520

### ISSUE THREAD

**Issue by doomsat** [OpenVisionE2/openvision-development-platform#10]
**Open Vision revision**
Open Vision 10.1-r164

**STB name**
DM520

**Logs**
[log.do_compile.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4766215/log.do_compile.log)

**Describe the bug**
fails when compiling kernel-module-extrawlan-rtl8189es
ioctl_cfg80211.c:38:10: fatal error: uapi/linux/nl80211.h: No such file or directory
#include <uapi/linux/nl80211.h>

Compiling the Feeds is the problem, compiling the image is fine.

I also ran cleanup.sh script and deleted the whole Build folder and rerun image.sh to make sure its clean again, only the feed fails when compiling kernel-module-extrawlan-rtl8189es

**Comment by doomsat** [comment]
had to exclude it from openvision-enigma2-feeds in order to complete the feeds build.

`	${@bb.utils.contains("MACHINE_FEATURES", "sh4stb", "", "kernel-module-extrawlan-rtl8189es", d)} \`

**Comment by kueken** [comment]
The patch would only have to be adjusted because it also applies to Kernel 3.4
https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/recipes-connectivity/ralink/kernel-module-extrawlan-rtl8189es/rtl8189es-kernel-3.2.patch#L9
Try to adapt it locally, it should work

**Comment by doomsat** [comment]
it didn't work, tried to only `#include <linux/nl80211.h>` and it compiled fine, i dont know why its like it is not recognizing the else in the if statement. even tried with if statement without else it worked, whenever `#include <uapi/linux/nl80211.h>` is there it fails... this is strange :/

**Comment by kueken** [comment]
The patch runs empty because of the kernel assignment.
There must also be inserted according to 3.5
`+#if (LINUX_VERSION_CODE < KERNEL_VERSION(3, 3, 0))`
`+#if (LINUX_VERSION_CODE < KERNEL_VERSION(3, 5 0))`

**Comment by doomsat** [comment]
yup, that worked just fine, the patch rtl8189es-kernel-3.2.patch need to fixed then.

Thanks
