### ISSUE TITLE
OV 10.2 Image for dm800sev2 does not boot

### ISSUE THREAD

**Issue by dryasser123** [OpenVisionE2/openvision-development-platform#100]
Terminal does not give me any Error during building Image for dm800sev2 , but the image does not boot 
[20201229165950.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5755073/20201229165950.log)

**Comment by persianpros** [comment]
Try changing the defconfig: https://github.com/OpenVisionE2/meta-dreambox/commits/develop/recipes-bsp/linux/linux-dreambox-3.2/dm800sev2

Probably one of the new defconfig changes is responsible.

Let us know which please.

**Comment by dryasser123** [comment]
I changed most of the defconfig. Every time change one line and build an image , nor image was booted . if you can give me the most suitable changes for the defconfig and  i will build the image according to it and told you by the results , many thanks
[defconfig.zip](https://github.com/OpenVisionE2/openvision-development-platform/files/5758840/defconfig.zip)

**Comment by dryasser123** [comment]
still the OV image unbootabale for dm800sev2 , any suggestion ?

**Comment by persianpros** [comment]
What's the output of "lsmod"?

**Comment by dryasser123** [comment]
What's the ''Ismod'' Mr.Persianpros Idon't Know it. Thank you for replay

**Comment by persianpros** [comment]
Telnet to your STB and enter "lsmod" as a command.

**Comment by persianpros** [comment]
Try this image: https://www.mediafire.com/file/nuxp72f57pu7awn/openvision-enigma2-develop-english-python2-7.6-r251-dm800_nfi.zip/file

**Comment by dryasser123** [comment]
Download not available
This file can not be downloaded because there was a problem with the upload. If possible, contact the person uploading the file to ask them to upload it again.

**Comment by persianpros** [comment]
Try https://www.mediafire.com/file/c7dvhprd4qpzapl/openvision-enigma2-develop-multilanguage-python2-10.2-r323-dm800sev2_nfi.zip/file

**Comment by dryasser123** [comment]
Mr./ Persianpros the image dosen't boot on Internal Flash .but booted well and worked on external Flash (Barry Allen)
What's the problem with this box ? Many thanks'

**Comment by persianpros** [comment]
I have no idea at the moment, all I know is dreambox has very bad kernel support and when we change defconfig it may break dreambox and we don't have dreambox in our team.

Try https://www.mediafire.com/file/g0asid0c3qfhvtt/openvision-enigma2-develop-multilanguage-python2-10.2-r324-dm800sev2_nfi.zip/file

**Comment by dryasser123** [comment]
OV 10.2-r324 doesn't boot , I removed Internal HDD and reflushed the Image but it doesn't boot , The image booted and worked on External flash (Barry Allen) .

**Comment by dryasser123** [comment]
The last version booted  for dm800sev2 is OV 9.3 -All version after that version doesn't booted

**Comment by dryasser123** [comment]
OV 10.2-r236 dosen't booted on internal or external flash for dm800sev2. I need some help please

**Comment by persianpros** [comment]
[defconfig.zip](https://github.com/OpenVisionE2/openvision-development-platform/files/5800659/defconfig.zip)

Try this defconfig, as I said we don't have this box in our team and the problem is in defconfig which needs to be fixed so you need to test different defconfigs which I give you.

**Comment by dryasser123** [comment]
You can consider me a tester until solving this problem , I tested all version of OV 10.2 on my box neither one was booted the last Image booted was 9.3, I will try your defconfig and I will told you . Thanks

**Comment by dryasser123** [comment]
Image upon your defconfig doesn't booted on Internal or External Flash . I am waiting for your next defconfig

**Comment by persianpros** [comment]
Compile and test a new image without changing anything.

Let us know if it boots.
