### ISSUE TITLE
ERROR: cifs-utils-6.11-r0 do_install

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#105]
Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:09
Sstate summary: Wanted 4589 Found 12 Missed 4577 Current 342 (0% match, 7% complete)
NOTE: Executing Tasks
ERROR: cifs-utils-6.11-r0 do_install: oe_runmake failed
ERROR: cifs-utils-6.11-r0 do_install: Execution of '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360' failed with exit code 1:
Making install in contrib
make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
Making install in request-key.d
make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
 /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
 /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
 /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/include'
 /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/sbin'
  /home/atef/openvision-development-platform/build/tmp/hosttools/install -c smbinfo '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
 /home/atef/openvision-development-platform/build/tmp/hosttools/install -c ../git/smb2-quota '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
 /home/atef/openvision-development-platform/build/tmp/hosttools/install -c -m 644 ../git/cifsidmap.h '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/include'
make  install-exec-hook
 /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin'
make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
(cd /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin && ln -sf mount.cifs mount.smb3)
/bin/bash: line 0: cd: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin: No such file or directory
make[3]: *** [Makefile:1503: install-exec-hook] Error 1
make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
make[2]: *** [Makefile:1382: install-exec-am] Error 2
make[2]: *** Waiting for unfinished jobs....
  /home/atef/openvision-development-platform/build/tmp/hosttools/install -c mount.cifs '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin'
make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
make[1]: *** [Makefile:1304: install-am] Error 2
make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
make: *** [Makefile:994: install-recursive] Error 1
WARNING: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360:201 exit 1 from 'exit 1'
WARNING: Backtrace (BB generated script): 
	#1: bbfatal_log, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 201
	#2: die, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 182
	#3: oe_runmake, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 171
	#4: autotools_do_install, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 162
	#5: do_install, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 154
	#6: main, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 205

Backtrace (metadata-relative locations):
	#1: bbfatal_log, /home/atef/openvision-development-platform/openembedded-core/meta/classes/logging.bbclass, line 72
	#2: die, /home/atef/openvision-development-platform/openembedded-core/meta/classes/base.bbclass, line 56
	#3: oe_runmake, /home/atef/openvision-development-platform/openembedded-core/meta/classes/base.bbclass, line 65
	#4: autotools_do_install, /home/atef/openvision-development-platform/openembedded-core/meta/classes/autotools.bbclass, line 247
	#5: do_install, autogenerated, line 2
ERROR: Logfile of failure stored in: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/log.do_install.1614360
Log data follows:
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/libtool/libtool-cross_2.4.6.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_10.2.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/libtool/libtool-native_2.4.6.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gnu-config/gnu-config_git.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-core/glibc/glibc_2.32.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/autoconf/autoconf_2.69.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/automake/automake_1.16.2.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_10.2.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/meta-openembedded/meta-networking/recipes-support/libtalloc/libtalloc_2.3.1.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['libtool-cross', 'patch-native', 'gcc-cross-mipsel', 'libtool-native', 'pseudo-native', 'quilt-native', 'gnu-config-native', 'glibc', 'autoconf-native', 'pkgconfig-native', 'automake-native', 'gcc-runtime', 'libtalloc', 'texinfo-dummy-native', 'binutils-cross-mipsel', 'attr-native', 'linux-libc-headers', 'libgcc', 'zlib-native', 'libmpc-native', 'mpfr-native', 'flex-native', 'gmp-native', 'xz-native', 'm4-native', 'python3', 'gettext-minimal-native', 'zlib', 'openssl', 'sqlite3', 'opkg-utils', 'libnsl2', 'libffi', 'libtirpc', 'util-linux', 'gdbm', 'bzip2', 'readline', 'libxcrypt', 'xz', 'libpam', 'bash-completion', 'ncurses', 'libcap-ng', 'cracklib', 'flex']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| NOTE: make -j 4 DESTDIR=/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image install
| Making install in contrib
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| Making install in request-key.d
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[3]: Nothing to be done for 'install-exec-am'.
| make[3]: Nothing to be done for 'install-data-am'.
| make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[3]: Nothing to be done for 'install-exec-am'.
| make[3]: Nothing to be done for 'install-data-am'.
| make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/include'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/sbin'
|   /home/atef/openvision-development-platform/build/tmp/hosttools/install -c smbinfo '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/install -c ../git/smb2-quota '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/install -c -m 644 ../git/cifsidmap.h '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/include'
| make  install-exec-hook
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin'
| make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| (cd /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin && ln -sf mount.cifs mount.smb3)
| /bin/bash: line 0: cd: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin: No such file or directory
| make[3]: *** [Makefile:1503: install-exec-hook] Error 1
| make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make[2]: *** [Makefile:1382: install-exec-am] Error 2
| make[2]: *** Waiting for unfinished jobs....
|   /home/atef/openvision-development-platform/build/tmp/hosttools/install -c mount.cifs '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin'
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make[1]: *** [Makefile:1304: install-am] Error 2
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| ERROR: oe_runmake failed
| make: *** [Makefile:994: install-recursive] Error 1
| WARNING: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360:201 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 201
| 	#2: die, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 182
| 	#3: oe_runmake, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 171
| 	#4: autotools_do_install, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 162
| 	#5: do_install, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 154
| 	#6: main, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 205
| ERROR: Execution of '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360' failed with exit code 1:
| Making install in contrib
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| Making install in request-key.d
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[3]: Nothing to be done for 'install-exec-am'.
| make[3]: Nothing to be done for 'install-data-am'.
| make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib/request-key.d'
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[3]: Nothing to be done for 'install-exec-am'.
| make[3]: Nothing to be done for 'install-data-am'.
| make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build/contrib'
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/include'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/sbin'
|   /home/atef/openvision-development-platform/build/tmp/hosttools/install -c smbinfo '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/install -c ../git/smb2-quota '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/bin'
|  /home/atef/openvision-development-platform/build/tmp/hosttools/install -c -m 644 ../git/cifsidmap.h '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/usr/include'
| make  install-exec-hook
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin'
| make[3]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| (cd /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin && ln -sf mount.cifs mount.smb3)
| /bin/bash: line 0: cd: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin: No such file or directory
| make[3]: *** [Makefile:1503: install-exec-hook] Error 1
| make[3]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make[2]: *** [Makefile:1382: install-exec-am] Error 2
| make[2]: *** Waiting for unfinished jobs....
|   /home/atef/openvision-development-platform/build/tmp/hosttools/install -c mount.cifs '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/image/sbin'
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make[1]: *** [Makefile:1304: install-am] Error 2
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/build'
| make: *** [Makefile:994: install-recursive] Error 1
| WARNING: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360:201 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 201
| 	#2: die, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 182
| 	#3: oe_runmake, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 171
| 	#4: autotools_do_install, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 162
| 	#5: do_install, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 154
| 	#6: main, /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/cifs-utils/6.11-r0/temp/run.do_install.1614360, line 205
| 
| Backtrace (metadata-relative locations):
| 	#1: bbfatal_log, /home/atef/openvision-development-platform/openembedded-core/meta/classes/logging.bbclass, line 72
| 	#2: die, /home/atef/openvision-development-platform/openembedded-core/meta/classes/base.bbclass, line 56
| 	#3: oe_runmake, /home/atef/openvision-development-platform/openembedded-core/meta/classes/base.bbclass, line 65
| 	#4: autotools_do_install, /home/atef/openvision-development-platform/openembedded-core/meta/classes/autotools.bbclass, line 247
| 	#5: do_install, autogenerated, line 2
ERROR: Task (/home/atef/openvision-development-platform/meta-openembedded/meta-networking/recipes-support/cifs/cifs-utils_6.11.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4231 tasks of which 1567 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-openembedded/meta-networking/recipes-support/cifs/cifs-utils_6.11.bb:do_install
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:104: feed] Error 1

Done, the compiled image is in build/tmp/deploy/images/dm820 folder!
It's a zipped file like openvision-enigma2-extralanguage-10-r327-dm820.zip

Compile time was 72 minutes and 59 seconds.
Fast compiling would be less than 60 minutes.
atef@atef-ganm:~/openvision-development-platform$

**Comment by petrkr** [comment]
For me it work compilation, but did not create .zip file. rest is uploaded at https://openvision.yacp.net/images/dm820/

You can try rename/delete build folder and try again. Actually currently is RED code, so it means build folder would need to be cleaned up.


```
Initialising tasks: 100% |###########################################################################################| Time: 0:00:08
Sstate summary: Wanted 2846 Found 719 Missed 2127 Current 2085 (25% match, 56% complete)
NOTE: Executing Tasks
WARNING: enigma2-plugin-extensions-openmultiboot-gitAUTOINC+8d2f2b893d-r0 do_populate_sysroot: File '/usr/lib/enigma2/python/Plugins/Extensions/OpenMultiboot/ubi_reader/ubifs/lzo.so' from enigma2-plugin-extensions-openmultiboot was already stripped, this will prevent future debugging!
WARNING: enigma2-plugin-systemplugins-crossepg-0.8.7+gitrAUTOINC+d43c59d56c-r0 do_populate_sysroot: File '/usr/lib/python2.7/lib-dynload/_crossepg.so' from enigma2-plugin-systemplugins-crossepg was already stripped, this will prevent future debugging!
WARNING: enigma2-plugin-systemplugins-crossepg-0.8.7+gitrAUTOINC+d43c59d56c-r0 do_populate_sysroot: File '/usr/lib/libcrossepg.so' from enigma2-plugin-systemplugins-crossepg was already stripped, this will prevent future debugging!
NOTE: Tasks Summary: Attempted 12350 tasks of which 6813 didn't need to be rerun and all succeeded.

Summary: There were 3 WARNING messages shown.

Done, the compiled image is in build/tmp/deploy/images/dm820 folder!
It's a zipped file like openvision-enigma2-extralanguage-10-r328-dm820.zip

Compile time was 46 minutes and 30 seconds.
Fast compiling would be less than 60 minutes.
```

**Comment by persianpros** [comment]
@petrkr 

Some images are in tar.xz and tar.gz images so we don't compress them again in zip :)
