### ISSUE TITLE
sh4 servicemp3epl problem

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#108]
Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 2186 Found 72 Missed 2114 Current 313 (3% match, 15% complete)
NOTE: Executing Tasks
WARNING: linux-sh4-spark-2.6.32.71-stm24-0217-openvision do_fetch: Checksum mismatch for local file /home/atef/openvision-development-platform/sources/stmicro.tar.gz
Cleaning and trying again.
WARNING: linux-sh4-spark-2.6.32.71-stm24-0217-openvision do_fetch: Renaming /home/atef/openvision-development-platform/sources/stmicro.tar.gz to /home/atef/openvision-development-platform/sources/stmicro.tar.gz_bad-checksum_3ec2c10cd428c58b26cfab9ac40e346891d89ad08248cbe9de7ea28f4aff2752
ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: Unable to install packages. Command '/home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/opkg.conf -t /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/temp/ipktemp/ -o /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install aio-grab avahi-daemon base-passwd ca-certificates cifs-utils cronie dhrystone distro-feed-configs dropbear dvbfetool e2fsprogs-e2fsck e2fsprogs-mke2fs e2fsprogs-tune2fs enigma2 enigma2-locale-meta enigma2-plugin-extensions-audiosync enigma2-plugin-extensions-autobackup enigma2-plugin-extensions-cutlisteditor enigma2-plugin-extensions-dreamirc enigma2-plugin-extensions-epgimport enigma2-plugin-extensions-epgrefresh enigma2-plugin-extensions-filecommander enigma2-plugin-extensions-graphmultiepg enigma2-plugin-extensions-historyzapselector enigma2-plugin-extensions-keyadder enigma2-plugin-extensions-mediaplayer enigma2-plugin-extensions-mediascanner enigma2-plugin-extensions-moviecut enigma2-plugin-extensions-openwebif enigma2-plugin-extensions-openwebif-themes enigma2-plugin-extensions-pictureplayer enigma2-plugin-extensions-reconstructapsc enigma2-plugin-extensions-socketmmi enigma2-plugin-extensions-tmbd enigma2-plugin-skins-octetfhd enigma2-plugin-softcams-oscam enigma2-plugin-systemplugins-autobouquetsmaker enigma2-plugin-systemplugins-cablescan enigma2-plugin-systemplugins-commoninterfaceassignment enigma2-plugin-systemplugins-fastscan enigma2-plugin-systemplugins-hdmicec enigma2-plugin-systemplugins-hotplug enigma2-plugin-systemplugins-mountmanager enigma2-plugin-systemplugins-networkbrowser enigma2-plugin-systemplugins-osdpositionsetup enigma2-plugin-systemplugins-positionersetup enigma2-plugin-systemplugins-satfinder enigma2-plugin-systemplugins-sh4boostercontrol enigma2-plugin-systemplugins-softwaremanager enigma2-plugin-systemplugins-terrestrialscan enigma2-plugin-systemplugins-videomode enigma2-plugin-systemplugins-videotune enigma2-plugin-systemplugins-wirelesslan enigma2-plugin-systemplugins-xmlupdate fakelocale frequency-xml-list-atsc frequency-xml-list-cables frequency-xml-list-satellites frequency-xml-list-terrestrial frequency-xml-list-unicable glibc-binary-localedata-en-gb hdparm kernel-module-autofs4 kernel-module-block2mtd kernel-module-fuse kernel-module-ipv6 kernel-params libavahi-client libcrypto libcrypto-compat modutils-loadscript nfs-utils nfs-utils-client ntpdate openssh-sftp openssh-sftp-server openvision-core-plugin openvision-extra-feed-config opkg packagegroup-base packagegroup-core-boot parted python-ipaddress python-netifaces run-postinsts sdparm settings-autorestore shadow tuxbox-common tuxbox-links tzdata util-linux-ionice util-linux-mount volatile-media vsftpd wget' returned 20:
 * Solver encountered 20 problem(s):
 * Problem 1/20:
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2

 * Problem 2/20:
 *   - package enigma2-plugin-extensions-audiosync-git6927+9e53a40-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-audiosync

 * Problem 3/20:
 *   - package enigma2-plugin-systemplugins-terrestrialscan-git2+73e709b-r0.spark requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-systemplugins-terrestrialscan

 * Problem 4/20:
 *   - package enigma2-plugin-systemplugins-xmlupdate-git2667+b5d501e-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-systemplugins-xmlupdate

 * Problem 5/20:
 *   - package enigma2-plugin-extensions-keyadder-2.5+git33+ec27425-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-keyadder

 * Problem 6/20:
 *   - package enigma2-plugin-systemplugins-autobouquetsmaker-3.1+git830+8562b0c-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-systemplugins-autobouquetsmaker

 * Problem 7/20:
 *   - package enigma2-plugin-extensions-autobackup-2.0+git169+3a80ac0-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-autobackup

 * Problem 8/20:
 *   - package enigma2-plugin-extensions-openwebif-git3961+511b5ed-r0.spark requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-openwebif

 * Problem 9/20:
 *   - package enigma2-plugin-extensions-epgimport-1.0+git231+e4ab3fc-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-epgimport

 * Problem 10/20:
 *   - package enigma2-plugin-extensions-tmbd-git72+16d80bb-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-tmbd

 * Problem 11/20:
 *   - package enigma2-plugin-extensions-moviecut-git2+73e709b-r0.spark requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-moviecut

 * Problem 12/20:
 *   - package enigma2-plugin-extensions-filecommander-2.0+git155+be94d55-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-filecommander

 * Problem 13/20:
 *   - package enigma2-plugin-extensions-epgrefresh-git6927+9e53a40-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-epgrefresh

 * Problem 14/20:
 *   - package enigma2-plugin-extensions-dreamirc-git6927+9e53a40-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-dreamirc

 * Problem 15/20:
 *   - package enigma2-plugin-systemplugins-mountmanager-git37+a79a63c-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-systemplugins-mountmanager

 * Problem 16/20:
 *   - package enigma2-plugin-systemplugins-networkbrowser-git2+73e709b-r0.spark requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-systemplugins-networkbrowser

 * Problem 17/20:
 *   - package enigma2-plugin-extensions-historyzapselector-git17+0c7f738-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-historyzapselector

 * Problem 18/20:
 *   - package enigma2-plugin-extensions-reconstructapsc-git6927+9e53a40-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-reconstructapsc

 * Problem 19/20:
 *   - package enigma2-plugin-extensions-openwebif-themes-git3961+511b5ed-r0.spark requires enigma2-plugin-extensions-openwebif, but none of the providers can be installed
 *   - package enigma2-plugin-extensions-openwebif-git3961+511b5ed-r0.spark requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-extensions-openwebif-themes

 * Problem 20/20:
 *   - package enigma2-plugin-skins-octetfhd-git291+a50a721-r0.all requires enigma2-plugin-systemplugins-weathercomponenthandler, but none of the providers can be installed
 *   - package enigma2-plugin-systemplugins-weathercomponenthandler-git6927+9e53a40-r0.sh4 requires enigma2, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides virtual/enigma2-mediaservice needed by enigma2-develop+git23203+4ba32fe-r0.spark
 * 
 * Solution 1:
 *   - do not ask to install a package providing enigma2-plugin-skins-octetfhd

 * opkg_finalize_intercepts: Failed to open dir /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/temp/ipktemp//opkg-rXBYe7/opkg-intercept-M6rev4: No such file or directory.
 * rm_r: Failed to open dir /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/temp/ipktemp//opkg-rXBYe7/opkg-intercept-M6rev4: No such file or directory.
 * rm_r: Failed to open dir /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/temp/ipktemp//opkg-rXBYe7: No such file or directory.
 * rm_r: Failed to open dir /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/rootfs//var/cache/opkg/volatile: No such file or directory.

ERROR: Logfile of failure stored in: /home/atef/openvision-development-platform/build/tmp/work/spark-oe-linux/openvision-enigma2-image/1.0-r0/temp/log.do_rootfs.312688
ERROR: Task (/home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7595 tasks of which 1599 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:100: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/spark folder!
It's a zipped file like openvision-enigma2-extralanguage-10.2-r332-spark.zip

Compile time was 90 minutes and 35 seconds.
Fast compiling would be less than 60 minutes.
atef@atef-ganm:~/openvision-development-platform$

**Comment by persianpros** [comment]
For some unknown reason enigma2-plugin-systemplugins-servicemp3epl is empty

**Comment by persianpros** [comment]
Fixed
