### ISSUE TITLE
glibc 2.25 bb do package failed 

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#109]
Sstate summary: Wanted 2391 Found 0 Missed 2391 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
ERROR: Task (/home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc_2.25.bb:do_package) failed with exit code '134'
NOTE: Tasks Summary: Attempted 1184 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc_2.25.bb:do_package
make: *** [Makefile:100: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/spark folder!
It's a zipped file like openvision-enigma2-extralanguage-10.2-r336-spark.zip

Compile time was 44 minutes and 44 seconds.
Fast compiling would be less than 60 minutes.
atef@atef-ganm:~/openvision-development-platform$

**Comment by persianpros** [comment]
Use cleanup.sh (Build) first then post logs, these are not related to us.
