### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ctomgr** [OpenVisionE2/openvision-development-platform#11]
Hi!
I try to compile openvision on Ubuntu 18.04.3  and i have this error:

> Makefile:116: recipe for target 'image' failed
> make: *** [image] Error 1
> Building image for k2pro
> ERROR: Unable to start bitbake server (None)
> ERROR: Server log for this session (/home/unkown/openvision-development-platform/build/bitbake-cookerdaemon.log):
> --- Starting bitbake server pid 6192 at 2019-10-06 12:25:42.470888 ---
> ERROR: ParseError at /home/unkown/openvision-development-platform/meta-linkdroid/conf/machine/include/mecool.inc:13: Could not include required file conf/machine/include/arm/arch-armv8.inc
> ...............................................................................................................................................
> Makefile:116: recipe for target 'image' failed
> make: *** [image] Error 1

**Comment by persianpros** [comment]
Hi,

You need to use 7.3 for meta-linkdroid as 9.2 isn't read for all and it's for developers only.
