### ISSUE TITLE
Forever_9898hd  | error 

### ISSUE THREAD

**Issue by alkap007** [OpenVisionE2/openvision-development-platform#11]
NOTE: Executing Tasks
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-branding-gitAUTOINC+b8c8111240-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-plugin-skins-pli-hd-0.1+gitAUTOINC+bec5aa82d6-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-module-1.0-openvision do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-module-1.0-openvision do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-module-1.0-openvision do_package_write_ipk: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-module-1.0-openvision do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-bootlogo-1.0-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-version-info-10.1-r164 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-sh4+gitAUTOINC+452b9b3298-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: bitratecalc-gitAUTOINC+d9a238f7dc-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: bitratecalc-gitAUTOINC+d9a238f7dc-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-autobouquetsmaker-3.1+gitAUTOINC+1992bc246b-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: bitratecalc-gitAUTOINC+d9a238f7dc-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-autobouquetsmaker-3.1+gitAUTOINC+1992bc246b-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: bitratecalc-gitAUTOINC+d9a238f7dc-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: bitratecalc-gitAUTOINC+d9a238f7dc-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: bitratecalc-gitAUTOINC+d9a238f7dc-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugins-gitAUTOINC+14dcdcdfc0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugins-gitAUTOINC+14dcdcdfc0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-autobouquetsmaker-3.1+gitAUTOINC+1992bc246b-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-autobouquetsmaker-3.1+gitAUTOINC+1992bc246b-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-plugin-systemplugins-autobouquetsmaker-3.1+gitAUTOINC+1992bc246b-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-autobouquetsmaker-3.1+gitAUTOINC+1992bc246b-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugin-systemplugins-servicemp3epl-gitAUTOINC+1006d56e00-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugins-gitAUTOINC+14dcdcdfc0-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_install: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-plugins-gitAUTOINC+14dcdcdfc0-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-plugins-gitAUTOINC+14dcdcdfc0-r0 do_package: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: enigma2-plugins-gitAUTOINC+14dcdcdfc0-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: enigma2-alliance-plugins-gitAUTOINC+5fa9be28a3-r0 do_populate_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_prepare_recipe_sysroot: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-alsa-lib.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-util-linux.populate_sysroot not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64-util-linux-native.populate_sysroot not found in x86_64 (variant '')?
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: Manifest /home/alkap/openvision-development-platform/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-ffmpeg.package_write_ipk not found in forever_9898hd sh4 sh allarch x86_64_x86_64-nativesdk (variant '')?
ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: No manifest generated from: ffmpeg in /home/alkap/openvision-development-platform/meta-openvision/recipes-multimedia/ffmpeg/ffmpeg_4.2.3.bb
ERROR: Logfile of failure stored in: /home/alkap/openvision-development-platform/build/tmp/work/forever_9898hd-oe-linux/openvision-enigma2-image/1.0-r0/temp/log.do_rootfs.6325
ERROR: Task (/home/alkap/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7098 tasks of which 6910 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/alkap/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs
Summary: There were 78 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:98: recipe for target 'image' failed
make: *** [image] Error 1

Done, the compiled image is in build/tmp/deploy/images/forever_9898hd folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r164-forever_9898hd.zip
alkap@Linuxx:~/openvision-development-platform$

**Comment by persianpros** [comment]
Please follow bug report template.

P.S. forever images are not ready anyway.

**Comment by alkap007** [comment]
thanks
