### ISSUE TITLE
ERROR: udev-extraconf-1.1-r0 do_install

### ISSUE THREAD

**Issue by elhawaryna** [OpenVisionE2/openvision-development-platform#12]
OTE: Executing Tasks
ERROR: udev-extraconf-1.1-r0 do_install: Execution of '/home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/temp/run.do_install.600' failed with exit code 1:
install: cannot stat '/home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/automount.rules': No such file or directory
WARNING: /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/temp/run.do_install.600:1 exit 1 from 'install -m 0644 /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/automount.rules /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/image/etc/udev/rules.d/automount.rules'

ERROR: Logfile of failure stored in: /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/temp/log.do_install.600
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['virtual:native:/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_10.1.bb:do_populate_sysroot', '/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', '/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_10.1.bb:do_populate_sysroot', '/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-core/glibc/glibc_2.31.bb:do_populate_sysroot', 'virtual:native:/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['patch-native', 'gcc-cross-mipsel', 'quilt-native', 'gcc-runtime', 'glibc', 'pseudo-native', 'gnu-config-native', 'libtool-native', 'libmpc-native', 'flex-native', 'gmp-native', 'binutils-cross-mipsel', 'mpfr-native', 'texinfo-dummy-native', 'xz-native', 'zlib-native', 'linux-libc-headers', 'automake-native', 'autoconf-native', 'libgcc', 'attr-native', 'm4-native', 'gettext-minimal-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| install: cannot stat '/home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/automount.rules': No such file or directory
| WARNING: /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/temp/run.do_install.600:1 exit 1 from 'install -m 0644 /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/automount.rules /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/image/etc/udev/rules.d/automount.rules'
| ERROR: Execution of '/home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/temp/run.do_install.600' failed with exit code 1:
| install: cannot stat '/home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/automount.rules': No such file or directory
| WARNING: /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/temp/run.do_install.600:1 exit 1 from 'install -m 0644 /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/automount.rules /home/elhawary/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/udev-extraconf/1.1-r0/image/etc/udev/rules.d/automount.rules'
| 
ERROR: Task (/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-core/udev/udev-extraconf_1.1.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2161 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-core/udev/udev-extraconf_1.1.bb:do_install
Summary: There were 8 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Error 1

**Comment by doomsat** [comment]
I faced this also, it requires automount.rules and its not available in udev-extraconf and not even called in the recipe, i wonder where it get called from.

i was building feed for DM900

**Comment by doomsat** [comment]
specify for witch receiver you are building, and is it feed or image?

**Comment by elhawaryna** [comment]
for Dreambox820

**Comment by kueken** [comment]
rebuild with cleanup build folder?

**Comment by elhawaryna** [comment]
He pointed out to a friend of mine that did this, I rebuilt and waited for the result, thank you

**Comment by elhawaryna** [comment]
Repeat again
RROR: Task (/home/elhawary/Desktop/openvision-development-platform/openembedded-core/meta/recipes-core/udev/udev-extraconf_1.1.bb:do_install) failed with exit code '1'

**Comment by kueken** [comment]
https://github.com/OpenVisionE2/openvision-development-platform/commit/18a3f82b22b03ce53c87f23d88c6e17b9840de47

seems like too much has been lost, I'll have a look

**Comment by elhawaryna** [comment]
There is a mistake that happened two days ago
https://github.com/OpenVisionE2/openvision-development-platform/commit/18a3f82b22b03ce53c87f23d88c6e17b9840de47

**Comment by kueken** [comment]
;-)
I wrote it too, but it's not so easy.
This whole thing with mdev to udev leads to some problems.
Older boxes also have a much slower boot time.
The error here could also come from the file system

**Comment by doomsat** [comment]
in  openembedded/meta/recipes-core/udev
file udev-extraconf_1.1.bb
`SRC_URI = " \
       file://automount.rules \
       file://mount.sh \
       file://mount.blacklist \
       file://autonet.rules \
       file://network.sh \
       file://localextra.rules \`

it includes the rules and blacklist files, in udev located at meta-openvision/recipes-core/udev

file udev-extraconf_1.%.bbappend calls only for mount.sh, if all the files above are needed, then they should be included in udev-extraconf_1.%.bbappend

i compiled udev alone and it seems to build fine

**Comment by kueken** [comment]
Yes, you would have to follow pli, but still look first.
https://github.com/OpenPLi/openpli-oe-core/commit/b2407ed06ed86d0c61b98dcbf8b3e711af1d5790
I am not a friend of these quick changes ;-)

**Comment by elhawaryna** [comment]
Thank you very much I have all the files as previously mentioned in your reply to change I think I will wait for an update

**Comment by kueken** [comment]
hopefully fixed ;-)
