### ISSUE TITLE
ERROR: openvision-version-info-9.2-r51

### ISSUE THREAD

**Issue by audi06** [OpenVisionE2/openvision-development-platform#15]
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "debian-10"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "dm900"
DISTRO               = "openvision"
DISTRO_VERSION       = "upcoming"
TUNE_FEATURES        = "arm vfp cortexa15 neon vfpv4 callconvention-hard"
TARGET_FPU           = "hard"

> ERROR: openvision-version-info-9.2-r51 do_install: Taskhash mismatch b7f087a74bc346347a973291be07caa8e7727239c0e2b51d3eb8dc1917360db2 versus 64bc6096f36edaf8d163a2c63ef3469678a7553133f44c5d9b42a85245477ee1 for /home/dreamosat/OpenVision/upcoming/meta-openvision/recipes-openvision/openvision-version-info/openvision-version-info.bb:do_install

**Comment by audi06** [comment]
@persianpros 
Up
`ERROR: openvision-version-info-9.2-r54 do_install: Taskhash mismatch 25534e5c2a58e42ef6f4d1a93b70edd71ebf335f8b6535a78898e56656ca0d1a versus 323d25ed98b1c8604d8e1a6c7fab347f8e4df0dc5d95b03fa0fec4505f26122b for /home/dreamosat/OpenVision/upcoming/meta-openvision/recipes-openvision/openvision-version-info/openvision-version-info.bb:do_install
`

**Comment by persianpros** [comment]
As I said before in https://forum.openvision.tech/viewtopic.php?f=5&t=459 it's not important ;)
