### ISSUE TITLE
IOError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by jack2015** [OpenVisionE2/openvision-development-platform#18]
dm900 clone sim2.3

[eDVBVolumecontrol] Setvolume: raw: 100 100, -1db: 0 0
[eTuxttxtApp] enable caching
[Timezones] Warning: Classic time zone '(GMT+05:45) Kathmandu' (Asia/Katmandu) is not available in '/usr/share/zoneinfo/'!
[Timezones] Warning: Classic time zone '(GMT+11:30) Norfolk Island' (Pacific/Norfolk) is not available in '/usr/share/zoneinfo/'!
[Timezones] Warning: Enigma2 time zone does not match system time zone (area 'Asia' != 'Generic',zone 'Athens' != 'UTC'), setting system to Enigma2 time zone!
[Timezones] Error: The time zone 'Asia/Athens' is not available! Using 'UTC' instead.
[Timezones] Setting time zone to 'UTC'.
[keymapparser] keymap file /usr/share/enigma2/keytranslation.xml not found
nameservers: [[192, 168, 0, 1]]
read configured interface: {'bnep0': {'dhcp': True}, 'usb0': {'dhcp': False}, 'lo': {'dhcp': False}, 'wlan0': {'dhcp': True}, 'atml0': {'dhcp': True}, 'eth1': {'dhcp': True}, 'eth0': {'dhcp': True}}
self.ifaces after loading: {'eth0': {'preup': False, 'predown': False, 'ip': [192, 168, 0, 107], 'up': True, 'mac': u'00:09:34:27:b3:73', 'netmask': [255, 255, 255, 0], 'dhcp': True, 'bcast': [192, 168, 0, 255], 'gateway': [192, 168, 0, 1]}}
[eDboxLCD] setLCDBrightness 102
[eDboxLCD] setLCDBrightness 127
close failed in file object destructor:
[MAIN] executing main
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
close failed in file object destructor:
IOError: [Errno 16] Device or resource busy
Plugin SystemPlugins/MountManager failed to load: No module named MountManager.plugin
Plugin probably removed, but not cleanly in /usr/lib/enigma2/python/Plugins/SystemPlugins/MountManager

[enigma.19700101.debug.zip](https://github.com/OpenVisionE2/openvision-development-platform/files/4836502/enigma.19700101.debug.zip)

**Comment by persianpros** [comment]
Follow the issue template please.
