### ISSUE TITLE
Error Build  gstreamer1.0-plugins-base

### ISSUE THREAD

**Issue by OpenVu** [OpenVisionE2/openvision-development-platform#19]
ERROR: gstreamer1.0-plugins-base-1.17.0.1+gitAUTOINC+8b92d144a1-r0 do_configure: meson failed
ERROR: gstreamer1.0-plugins-base-1.17.0.1+gitAUTOINC+8b92d144a1-r0 do_configure: Execution of '/home/emcteam13/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/gstreamer1.0-plugins-base/1.17.0.1+gitAUTOINC+8b92d144a1-r0/temp/run.do_configure.3972' failed with exit code 1:
usage: meson [-h]
             {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite}
             ...
meson: error: unrecognized arguments: --disable-dispmanx
WARNING: /home/emcteam13/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/gstreamer1.0-plugins-base/1.17.0.1+gitAUTOINC+8b92d144a1-r0/temp/run.do_configure.3972:1 exit 1 from 'exit 1'

ERROR: Logfile of failure stored in: /home/emcteam13/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/gstreamer1.0-plugins-base/1.17.0.1+gitAUTOINC+8b92d144a1-r0/temp/log.do_configure.3972
Log data follows:
| DEBUG: Executing shell function do_configure
| NOTE: Executing meson -Dalsa=enabled -Dcdparanoia=enabled --disable-dispmanx -Dogg=enabled -Dopus=enabled -Dpango=enabled -Dtheora=enabled -Dvorbis=enabled...
| usage: meson [-h]
|              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite}
|              ...
| meson: error: unrecognized arguments: --disable-dispmanx
| ERROR: meson failed
| WARNING: /home/emcteam13/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/gstreamer1.0-plugins-base/1.17.0.1+gitAUTOINC+8b92d144a1-r0/temp/run.do_configure.3972:1 exit 1 from 'exit 1'
| ERROR: Execution of '/home/emcteam13/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/gstreamer1.0-plugins-base/1.17.0.1+gitAUTOINC+8b92d144a1-r0/temp/run.do_configure.3972' failed with exit code 1:
| usage: meson [-h]
|              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite}
|              ...
| meson: error: unrecognized arguments: --disable-dispmanx
| WARNING: /home/emcteam13/Desktop/openvision-development-platform/build/tmp/work/mips32el-oe-linux/gstreamer1.0-plugins-base/1.17.0.1+gitAUTOINC+8b92d144a1-r0/temp/run.do_configure.3972:1 exit 1 from 'exit 1'
| 
ERROR: Task (/home/emcteam13/Desktop/openvision-development-platform/meta-openvision/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_git.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3107 tasks of which 2176 didn't need to be rerun and 1 failed.

**Comment by persianpros** [comment]
Remove https://github.com/OpenVisionE2/meta-raspberrypi/blob/develop/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%25.bbappend from your local files.
