### ISSUE TITLE
Info key crash to display event details EPG

### ISSUE THREAD

**Issue by doomsat** [OpenVisionE2/openvision-development-platform#23]
**Open Vision revision**
OV 10.1-r170

**STB name**
DM900
DM520
since this is related to enigma2 I guess it's on all STBs

**Logs**
[enigma2_crash_2020-07-04_04-52-09.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4871989/enigma2_crash_2020-07-04_04-52-09.log)

**Describe the bug**

Pressing Info key should display the event details of the current event EPG.

This problem is not new, perhaps since r158, the problem is in enigma2, there was "issues" tab to open the issue in enigma2-openvision, so I opened it here.

**Comment by norhap** [comment]
unzip attach
FTP to EventView.py to  /usr/lib/enigma2/python/Screens/
restart enigma2
[EventView.zip](https://github.com/OpenVisionE2/openvision-development-platform/files/4872403/EventView.zip)

**Comment by doomsat** [comment]
[crashlog.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4872891/crashlog.log)

didn't work.

**Comment by norhap** [comment]
You have something wrong, the two crashes are different in broken lines ... they are different with respect to the original openvision (the one that I have uploaded) regarding its first crash.

**Comment by norhap** [comment]
the possible affected lines are 363 or 371, it does not coincide at all with their crash ... (line 346).

**Comment by doomsat** [comment]
i transferred eventview.py to screens folder, like you said, i restart enigma2 in debug mode to provide the log.

[crashlog.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4872979/crashlog.log)

**Comment by doomsat** [comment]
the issue is not solved why close it?

**Comment by norhap** [comment]
you don't have the same EventView.py, we can't have an open problem with different code.

**Comment by doomsat** [comment]
ok i will have a fresh image install and i will reupload the file you provided and then provide the log.

**Comment by norhap** [comment]
https://github.com/OpenVisionE2/openvision-development-platform/files/4871989/enigma2_crash_2020-07-04_04-52-09.log
this is another code, impossible it is 346, in any case it would be 363 or 371

File "/usr/lib/enigma2/python/Screens/EventView.py", line 346, in __init__

**Comment by norhap** [comment]
> 
> 
> ok i will have a fresh image install and i will reupload the file you provided and then provide the log.

yes please, if you follow the GSOD with image updated and compiled by you, please do not hesitate to contact the log.

**Comment by doomsat** [comment]
here i provided two logs one as the original and one after transferring eventview.py

[original-OV-crash-log.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4873034/original-OV-crash-log.log)


[crashlog-after-modified-eventview.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4873035/crashlog-after-modified-eventview.log)

**Comment by doomsat** [comment]
I have readded the original log and got rid of unrelated stuff

**Comment by norhap** [comment]
I can't reproduce this problem, for me everything is fine
do you restore backup?

**Comment by doomsat** [comment]
No it is not a backup, I will recompile again from source and install the image send the logs again, since starting fresh ignore the original log from the first post

**Comment by norhap** [comment]
ok, you are a member of openvision.tech yousif666 ?

**Comment by doomsat** [comment]
just finished installing the image, i tested and it seems to work! i really have no idea how that happens since i already installed a fresh image before that, and even without using the modification to eventview.py, either i am going crazy or there is something wrong i am doing.

**Comment by norhap** [comment]
log of the first post is clear, the code does not match.
agree, watch it, any news keep me informed please.

**Comment by doomsat** [comment]
what was causing the problem is EPG translator plugin  :/
