### ISSUE TITLE
Bug report for Open Vision 10.1

### ISSUE THREAD

**Issue by Ntemis** [OpenVisionE2/openvision-development-platform#24]
**Open Vision revision**
Tell us it's OV 10.1-rx?

**STB name**
Check https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/Vision-metas.md and tell us what's your model exactly like you see in our "Vision-metas.md" file.

**smallflash/middleflash**
Is your model a smallflash or middleflash? You'll see this in the About screen.

**Enigma2**
Date is important.

**Logs**
We need some logs for understanding what's wrong and you could learn how to get them in https://forum.openvision.tech/viewtopic.php?f=15&t=446 but please don't remove sections from the crashlogs, sometimes we need all the logs or even a full dmesg to understand what's happening.

**Describe the bug**

**To Reproduce**
2. Click on '...'

**Expected behavior**

**Screenshots**

**Additional context**
WARNING: iso-codes-4.5.0-r0 do_fetch: Failed to fetch URL git://salsa.debian.org/iso-codes-team/iso-codes.git;protocol=http, attempting MIRRORS if available
ERROR: iso-codes-4.5.0-r0 do_fetch: Fetcher failure: Unable to find revision a36019e5014bff251f83d522ddcfebaecf52afd3 in branch master even from upstream
ERROR: iso-codes-4.5.0-r0 do_fetch: Fetcher failure for URL: 'git://salsa.debian.org/iso-codes-team/iso-codes.git;protocol=http'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/demetris/openvision-development-platform/build/tmp/work/all-oe-linux/iso-codes/4.5.0-r0/temp/log.do_fetch.28298
ERROR: Task (/home/demetris/openvision-development-platform/openembedded-core/meta/recipes-support/iso-codes/iso-codes_4.5.0.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2454 tasks of which 2351 didn't need to be rerun and 1 failed.

**Comment by persianpros** [comment]
It's a fetch error, not related to us.
