### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#25]
`Parsing of 3967 .bb files complete (3560 cached, 407 parsed). 5441 targets, 1004 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'unjffs2' (but /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/openmultiboot/enigma2-plugin-extensions-openmultiboot.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'unjffs2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['unjffs2']
NOTE: Runtime target 'enigma2-plugin-extensions-openmultiboot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['enigma2-plugin-extensions-openmultiboot', 'unjffs2']
ERROR: Required build target 'openvision-enigma2-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['openvision-enigma2-image', 'enigma2-plugin-extensions-openmultiboot', 'unjffs2']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/spark folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r178-spark.zip
atef@AtefGanm:~/openvision-development-platform$ 
`

**Comment by persianpros** [comment]
Please follow the issue template.

P.S. I just fixed the problem.
