### ISSUE TITLE
Unable to compile wetek play2

### ISSUE THREAD

**Issue by Ntemis** [OpenVisionE2/openvision-development-platform#26]
-e 
-e Updated.
-e 
-e Compiling Specific images, please wait ...
-e 
-e Enter your specific machine name exactly like what you see in Vision-metas.md
-e 
wetekplay2
-e 
-e Compiling wetekplay2 image, please wait ...
-e 
Generating /home/demetris/openvision-development-platform/build/env.source
Building image for wetekplay2
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/demetris/openvision-development-platform/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 31736 at 2019-12-29 20:28:28.601417 ---
ERROR: ParseError at /home/demetris/openvision-development-platform/meta-wetek/conf/machine/include/wetek-common.inc:7: Could not include required file conf/machine/include/arm/arch-armv8.inc

Makefile:102: recipe for target 'image' failed
make: *** [image] Error 1
-e 
-e Done, the compiled image is in build/tmp/deploy/images/wetekplay2 folder!
-e It's a zipped file like openvision-enigma2-upcoming-multilanguage-9.3-r75-wetekplay2.zip

**Comment by persianpros** [comment]
You need to use 7.3, Amlogic isn't ready for 9.3
