### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#28]
`Sstate summary: Wanted 4841 Found 0 Missed 4841 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
WARNING: enigma2-persianempire-plugins-gitAUTOINC+c8048775f9-r0 do_populate_sysroot: File '/usr/lib/enigma2/python/Plugins/Extensions/AirPlayer/atproxy' from enigma2-persianempire-plugins was already stripped, this will prevent future debugging!
WARNING: enigma2-persianempire-plugins-gitAUTOINC+c8048775f9-r0 do_populate_sysroot: File '/usr/lib/enigma2/python/Plugins/Extensions/AirPlayer/proxy' from enigma2-persianempire-plugins was already stripped, this will prevent future debugging!
ERROR: enigma2-plugin-extensions-yahooweather-1.2.+gitAUTOINC+f04f398ad7-r0 do_install: oe_runmake failed
ERROR: enigma2-plugin-extensions-yahooweather-1.2.+gitAUTOINC+f04f398ad7-r0 do_install: Execution of '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/temp/run.do_install.3629439' failed with exit code 1:
Making install in po
make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
make[2]: Nothing to be done for 'install-exec-am'.
xgettext -L python --add-comments="TRANSLATORS:" -d YahooWeather -s -o YahooWeather.pot ../*.py
for lang in de it tr; do \
	msgmerge --no-location -s -N -U $lang.po YahooWeather.pot; \
done
msgfmt -o de.mo de.po
msgfmt -o it.mo it.po
msgfmt -o tr.mo tr.po
../xml2po.py ../ >> YahooWeather.pot
/bin/bash: ../xml2po.py: /usr/bin/python: bad interpreter: No such file or directory
make[2]: *** [Makefile:478: YahooWeather.pot] Error 126
make[2]: *** Waiting for unfinished jobs....
........ done.
........ done.
........ done.
make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
make[1]: *** [Makefile:357: install-am] Error 2
make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
make: *** [Makefile:388: install-recursive] Error 1
WARNING: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/temp/run.do_install.3629439:1 exit 1 from 'exit 1'

ERROR: Logfile of failure stored in: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/temp/log.do_install.3629439
Log data follows:
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/libtool/libtool-cross_2.4.6.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_10.1.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/autoconf/autoconf_2.69.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/automake/automake_1.16.2.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/libtool/libtool-native_2.4.6.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gnu-config/gnu-config_git.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_10.1.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-core/glibc/glibc_2.31.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-core/gettext/gettext_0.20.2.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['libtool-cross', 'gcc-cross-mipsel', 'autoconf-native', 'automake-native', 'libtool-native', 'pseudo-native', 'gnu-config-native', 'gcc-runtime', 'glibc', 'gettext-native', 'quilt-native', 'patch-native', 'flex-native', 'xz-native', 'libmpc-native', 'linux-libc-headers', 'gmp-native', 'zlib-native', 'binutils-cross-mipsel', 'texinfo-dummy-native', 'mpfr-native', 'm4-native', 'libgcc', 'pkgconfig-native', 'gettext-minimal-native', 'attr-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| NOTE: make -j 8 DESTDIR=/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/image install
| Making install in po
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make[2]: Nothing to be done for 'install-exec-am'.
| xgettext -L python --add-comments="TRANSLATORS:" -d YahooWeather -s -o YahooWeather.pot ../*.py
| for lang in de it tr; do \
| 	msgmerge --no-location -s -N -U $lang.po YahooWeather.pot; \
| done
| msgfmt -o de.mo de.po
| msgfmt -o it.mo it.po
| msgfmt -o tr.mo tr.po
| ../xml2po.py ../ >> YahooWeather.pot
| /bin/bash: ../xml2po.py: /usr/bin/python: bad interpreter: No such file or directory
| make[2]: *** [Makefile:478: YahooWeather.pot] Error 126
| make[2]: *** Waiting for unfinished jobs....
| ........ done.
| ........ done.
| ........ done.
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make[1]: *** [Makefile:357: install-am] Error 2
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make: *** [Makefile:388: install-recursive] Error 1
| ERROR: oe_runmake failed
| WARNING: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/temp/run.do_install.3629439:1 exit 1 from 'exit 1'
| ERROR: Execution of '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/temp/run.do_install.3629439' failed with exit code 1:
| Making install in po
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make[2]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make[2]: Nothing to be done for 'install-exec-am'.
| xgettext -L python --add-comments="TRANSLATORS:" -d YahooWeather -s -o YahooWeather.pot ../*.py
| for lang in de it tr; do \
| 	msgmerge --no-location -s -N -U $lang.po YahooWeather.pot; \
| done
| msgfmt -o de.mo de.po
| msgfmt -o it.mo it.po
| msgfmt -o tr.mo tr.po
| ../xml2po.py ../ >> YahooWeather.pot
| /bin/bash: ../xml2po.py: /usr/bin/python: bad interpreter: No such file or directory
| make[2]: *** [Makefile:478: YahooWeather.pot] Error 126
| make[2]: *** Waiting for unfinished jobs....
| ........ done.
| ........ done.
| ........ done.
| make[2]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make[1]: *** [Makefile:357: install-am] Error 2
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/git/po'
| make: *** [Makefile:388: install-recursive] Error 1
| WARNING: /home/atef/openvision-development-platform/build/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/temp/run.do_install.3629439:1 exit 1 from 'exit 1'
| 
ERROR: Task (/home/atef/openvision-development-platform/meta-openvision/recipes-openvision/enigma2-plugins/enigma2-plugin-extensions-yahooweather.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9901 tasks of which 33 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/enigma2-plugins/enigma2-plugin-extensions-yahooweather.bb:do_install
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:103: feed] Error 1

Done, the compiled image is in build/tmp/deploy/images/dm820 folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r195-dm820.zip
atef@ganm:~/openvision-development-platform$ 
`

**Comment by persianpros** [comment]
This issue isn't following our issue template so we need to close it.
