### ISSUE TITLE
Build fail on wetek play 2 

### ISSUE THREAD

**Issue by Ntemis** [OpenVisionE2/openvision-development-platform#29]
|   INSTALL net/netfilter/xt_owner.ko
|   INSTALL net/netfilter/xt_multiport.ko
|   INSTALL net/netfilter/xt_mac.ko
|   INSTALL net/netfilter/xt_nat.ko
|   INSTALL net/netfilter/xt_limit.ko
|   INSTALL net/netfilter/xt_policy.ko
|   INSTALL net/netfilter/xt_recent.ko
|   INSTALL net/netfilter/xt_tcpmss.ko
|   INSTALL net/netfilter/xt_statistic.ko
|   INSTALL net/netfilter/xt_state.ko
|   INSTALL net/netfilter/xt_set.ko
|   INSTALL net/netfilter/xt_time.ko
|   INSTALL net/netfilter/xt_tcpudp.ko
|   INSTALL net/xfrm/xfrm_algo.ko
|   INSTALL net/sunrpc/auth_gss/rpcsec_gss_krb5.ko
|   INSTALL net/wireless/cfg80211.ko
|   INSTALL net/xfrm/xfrm_ipcomp.ko
|   INSTALL net/xfrm/xfrm_user.ko
|   INSTALL sound/core/snd-hrtimer.ko
|   INSTALL sound/core/snd-rawmidi.ko
|   INSTALL sound/core/snd-hwdep.ko
|   INSTALL sound/usb/6fire/snd-usb-6fire.ko
|   INSTALL sound/usb/caiaq/snd-usb-caiaq.ko
|   INSTALL sound/usb/misc/snd-ua101.ko
|   INSTALL sound/usb/snd-usb-audio.ko
|   INSTALL sound/usb/snd-usbmidi-lib.ko
|   DEPMOD  3.14.29
| install: cannot stat '/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/linux-wetek2/3.14.29-openvision/build/arch/arm64/boot/gxbb_p200_2G_wetek_play_2.dtb': No such file or directory
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home/demetris/openvision-development-platform/meta-wetek/recipes-bsp/linux/linux-wetek2_3.14.29.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3396 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/demetris/openvision-development-platform/meta-wetek/recipes-bsp/linux/linux-wetek2_3.14.29.bb:do_install
Summary: There were 68 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:102: recipe for target 'image' failed
make: *** [image] Error 1
-e 
-e Done, the compiled image is in build/tmp/deploy/images/wetekplay2 folder!
-e It's a zipped file like openvision-enigma2-new-multilanguage-9.3-r79-wetekplay2.zip

**Comment by Ntemis** [comment]
iscanner/dumper.py", line 166, in run
|     self._link(bin_path, introspection_obj)
|   File "/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/recipe-sysroot-native/usr/lib/gobject-introspection/giscanner/dumper.py", line 275, in _link
|     subprocess.check_call(args)
|   File "/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/recipe-sysroot-native/usr/lib/python3.7/subprocess.py", line 358, in check_call
|     retcode = call(*popenargs, **kwargs)
|   File "/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/recipe-sysroot-native/usr/lib/python3.7/subprocess.py", line 339, in call
|     with Popen(*popenargs, **kwargs) as p:
|   File "/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/recipe-sysroot-native/usr/lib/python3.7/subprocess.py", line 800, in __init__
|     restore_signals, start_new_session)
|   File "/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/recipe-sysroot-native/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: '../libtool': '../libtool'
| Makefile:2034: recipe for target 'Gst-0.10.gir' failed
| make[4]: *** [Gst-0.10.gir] Error 1
| make[4]: Leaving directory '/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/build/gst'
| Makefile:1572: recipe for target 'all-recursive' failed
| make[3]: *** [all-recursive] Error 1
| make[3]: Leaving directory '/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/build/gst'
| Makefile:909: recipe for target 'all' failed
| make[2]: *** [all] Error 2
| make[2]: Leaving directory '/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/build/gst'
| Makefile:747: recipe for target 'all-recursive' failed
| make[1]: *** [all-recursive] Error 1
| make[1]: Leaving directory '/home/demetris/openvision-development-platform/build/tmp/work/wetekplay2-oe-linux/gstreamer/0.10.36.1+gitAUTOINC+76fc67b18c-r0/build'
| Makefile:651: recipe for target 'all' failed
| make: *** [all] Error 2
| WARNING: exit code 1 from a shell command.
|
ERROR: Task (/home/demetris/openvision-development-platform/meta-openvision/recipes-multimedia/gstreamer-old/gstreamer_0.10.36.1.bb:do_compile) failed with exit code '1'

**Comment by persianpros** [comment]
I didn't try wetekplay2 on 9.3 yet but I just fixed another Amlogic meta: https://github.com/OpenVisionE2/meta-linkdroid/commit/3519c3edea4523167261e33df43b35f716083368

Still I can't compile gstreamer_0.10.36.1.bb so the build isn't ok for Amlogic yet.

**Comment by Ntemis** [comment]
I can try to help. Any logs?

**Comment by Ntemis** [comment]
@persianpros 
Any reason you have to use such an old version?
https://gstreamer.freedesktop.org/releases/1.16/#1.16.2
