### ISSUE TITLE
Fail in compiling kernel for DM900 image

### ISSUE THREAD

**Issue by doomsat** [OpenVisionE2/openvision-development-platform#29]
**Open Vision revision**
OV 10.1-r200

**STB name**
DM900

**Logs**
[log.do_compile.txt](https://github.com/OpenVisionE2/openvision-development-platform/files/5042855/log.do_compile.txt)

**Describe the bug**
linux-dreambox-3.14-openvision do_compile: oe_runmake failed, details in the log file above.

**Comment by kueken** [comment]
https://git.kernel.org/pub/scm/utils/dtc/dtc.git/commit/?id=0e9225eb0dfec51def612b928d2f1836b092bc7e
I think it needs a patch to remove the line.
You can try it locally first and if it works, insert the patch.

**Comment by persianpros** [comment]
Also https://github.com/openzfs/zfs/commit/af09c050e95bebbaeca52156218f3f91e8c9951a

**Comment by persianpros** [comment]
Ok it's not just dm920 it's almost all brands/models on Ubuntu 20.04.x LTS with GCC 10 so we need to apply something for all ...

**Comment by doomsat** [comment]
replacing YYLTYPE yylloc; with extern YYLTYPE yylloc; seems to be a work around, i am compiling now,

the change of YYLTYPE yylloc;  to extern YYLTYPE yylloc; is in dtc-lexer.l and dtc-parser.tab.c_shipped

**Comment by persianpros** [comment]
That needs to be done for all kernels which is not a good thing to do, I'm trying to find another way.

**Comment by persianpros** [comment]
OE devs have problem with this too: https://github.com/openembedded/openembedded-core/commit/951e859b1e8297970278c539e989b8a6d06a9cb3

Also CoreELEC: https://github.com/CoreELEC/CoreELEC/pull/242/commits/ee30cb355808d05203b0f9c6ced3c45f86184479

According to https://gcc.gnu.org/gcc-10/changes.html:

* GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking.

**Comment by persianpros** [comment]
For me fixed with https://github.com/OpenVisionE2/openvision-development-platform/commit/0dfe535b899109ded125de6a87f99f54f6a68235

Try it.

**Comment by doomsat** [comment]
I removed the build folder in order to fetch the new modifications but it didn't work, it failed again, I had to add **extern extern YYLTYPE yylloc;** in "dtc-parser.tab.c_shipped", in dtc-lexer.l it was removed based on the latest fetch.

**Comment by persianpros** [comment]
@doomsat 

I didn't test with dm9x0 yet as I'm compiling for some HiSilicon models and they're fine with my new commit.

You don't need to remove the build folder for this just clean the kernel using image.sh (Kernel-Clean) then choose Vision.

**Comment by kueken** [comment]
Hisi Kernel 4
Dream Kernel 3
So either patch the 3-kernel, or consider a rollback regarding OE_Core.
There is sure to be a patch for the gcc soon.

**Comment by persianpros** [comment]
Yeah I think OE devs would do something for this but my bbclass doesn't care about kernel version and it patches the moment find the file.

I'll test dm9x0 tomorrow and see if it needs more changes.

**Comment by petrkr** [comment]
For octagon sf4008 does not help...

```
| make: *** [Makefile:24: __sub-make] Error 2
| WARNING: /home/builder/openvision-development-platform/build/tmp/work/sf4008-oe-linux-gnueabi/linux-octagon/4.1.37-openvision/temp/run.do_compile.460230:1 exit 1 from 'exit 1'
| ERROR: Execution of '/home/builder/openvision-development-platform/build/tmp/work/sf4008-oe-linux-gnueabi/linux-octagon/4.1.37-openvision/temp/run.do_compile.460230' failed with exit code 1:
|   GEN     ./Makefile
| scripts/kconfig/conf  --silentoldconfig Kconfig
|   CHK     include/config/kernel.release
|   GEN     ./Makefile
|   CHK     include/generated/uapi/linux/version.h
|   CHK     include/generated/utsrelease.h
|   Using /home/builder/openvision-development-platform/build/tmp/work-shared/sf4008/kernel-source as source for kernel
|   SHIPPED scripts/dtc/dtc-parser.tab.c
|   HOSTCC  scripts/dtc/dtc-parser.tab.o
|   HOSTLD  scripts/dtc/dtc
| /home/builder/openvision-development-platform/build/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x50): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
| collect2: error: ld returned 1 exit status
| make[4]: *** [scripts/Makefile.host:100: scripts/dtc/dtc] Error 1
| make[3]: *** [/home/builder/openvision-development-platform/build/tmp/work-shared/sf4008/kernel-source/scripts/Makefile.build:403: scripts/dtc] Error 2
| make[2]: *** [/home/builder/openvision-development-platform/build/tmp/work-shared/sf4008/kernel-source/Makefile:555: scripts] Error 2

```


On ubuntu 18 works, but on 20 get's this error

**Comment by persianpros** [comment]
Please wait I'm working on this ...

**Comment by petrkr** [comment]
> Please wait I'm working on this ...

meanwhile I figured out one more problematic plugin, will try in ubuntu 20 (after fix dtc)... For now I have r203 built and working at ubuntu 18

**Comment by kueken** [comment]
Yes, with the error in the log further ahead.
This only shows the end of the log.
It is a gcc error and it seems that OE-Core is already working on it.

I think the error also occurs under Ubuntu 18, but there kernel <4.
I already said that I would suggest a rollback of the OE-Core as a solution until OE-Core has eliminated the error.
But I would stick with Ubuntu 18 in general.
Ubuntu 20 still seems a bit buggy

**Comment by petrkr** [comment]
> Yes, with the error in the log further ahead.
> This only shows the end of the log.
> It is a gcc error and it seems that OE-Core is already working on it.
> 
> I think the error also occurs under Ubuntu 18, but there kernel <4.
> I already said that I would suggest a rollback of the OE-Core as a solution until OE-Core has eliminated the error.
> But I would stick with Ubuntu 18 in general.
> Ubuntu 20 still seems a bit buggy

it's good to update anyway.. But right, hard-coded switch which says "unsupported version" should be done after new release is working fine...

But on other side, e2 is so specific thing which I think 99% peoples not build at themself and that 1% are mostly peoples like us, who can handle some build errors, just ask here to cooperate and make things faster...

**Comment by Hains** [comment]
Dm920 is building fine with latest OE-core and Ubuntu 20.04, with default gcc 9.3.0.

**Comment by persianpros** [comment]
Ok I just fixed kernel 3.x, updates are coming ;)

@Hains 

Yeah that would work but image.sh installs GCC 10 which is needed for some other kernels so updating is inevitable, OE devs have this problem too and they're working on it.

GCC 10 has some new defaults.

**Comment by Hains** [comment]
Yes OK, 
I just wanna say, dont' install gcc 10 as host compiler if you have any problem and the problem with gcc 10 isn't fixed yet.
Downgrade Ubuntu back to 18.04 and/or rollback OE-core is more work.
Now suffer almost all boxes due to a few boxes which require gcc 10 as host compiler.
Just my 2 cents.

**Comment by persianpros** [comment]
I'm changing all metas to have a new variable which is static and perfect for recipe management something to get rid of unreliable https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/recipes-openvision/images/openvision-enigma2-feed.bb#L16 (intoduced by PLi) once for all.

The new variable helps me to use it in the new bbclass to detect kernel 3.x too and current problem solved here in my OE but the meta updates are huge work and I'm working on them so fast without eating lunch to deliver it ASAP.

:+1:

**Comment by persianpros** [comment]
https://github.com/OpenVisionE2/openvision-development-platform/commit/a22a29475b4922fa1735e2337ab576747088ef13 should fix compile problem with 3.x kernels.

I didn't test 5.x or 2.x yet.

**Comment by petrkr** [comment]
Still same, as it's 4.x kernel. commented direct on commit

**Comment by persianpros** [comment]
HiSilicon 4.4.x is ok but let me try it for sf4008 and see what we need ...

**Comment by petrkr** [comment]
check commet https://github.com/OpenVisionE2/openvision-development-platform/issues/29#issuecomment-670990022 with stacktrace

**Comment by persianpros** [comment]
@petrkr 

Please check your build now, this time without if condition and without checking the kernel version so this one is better and if we wanted not to apply it we will check a specific kernel version.

**Comment by petrkr** [comment]
> @petrkr
> 
> Please check your build now, this time without if condition and without checking the kernel version so this one is better and if we wanted not to apply it we will check a specific kernel version.

Confirm it works.

Also can I lobby for 'btrfs' FS support  ? I already did my own build and it works

```
Btrfs loaded
root@sf4008:/etc# lsmod
Module                  Size  Used by
btrfs                 859061  0
```

**Comment by persianpros** [comment]
Yes we can enable it as module ;)
