### ISSUE TITLE
Octagon SF4008 blank screen - missing framebuffer drivers?

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#30]
Something gets wrong between release 91 and toda'ys r201. Linux boot's up, but there is not HDMI output nor LCD screen still says "booting".

SSH connection works, but when try run enigma2, there is missing framebuffer... I did clean build today

build "vision", now building "feed". Maybe it's connected?

Also using (as always did) Open Multiboot platform - Maybe some changes which could lead to unsupport that? I do not want burn that to flash cause I do not want brick it.

```
root@sf4008:~# enigma2
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 11
ENIGMA_DEBUG_LVL=3
<   360.6718> 10:42:54.4243 [gFBDC] no framebuffer available
Segmentation fault
```

**Comment by petrkr** [comment]
ha, since dmesg says nothing, but /var/log/dmesg has some usefull things
[r201-dmesg.txt](https://github.com/OpenVisionE2/openvision-development-platform/files/5045041/r201-dmesg.txt)

**Comment by persianpros** [comment]
Check https://github.com/OpenVisionE2/meta-octagon/commit/a0a2354fdbb39a2543c46aee339fbe838d95fb30#diff-02b5af348ed902916f9550c372e93c12 and try another driver (newer or older) as sf4008 has driver problem when OE changes.

**Comment by petrkr** [comment]
Will try, for now I just see different mode layout of module
```
root@sf4008:/mnt# modprobe --dump-modversions /lib/modules/4.1.37/kernel/ |grep layout
drivers/ fs/      net/     
root@sf4008:/mnt# modprobe --dump-modversions /lib/modules/4.1.37/kernel/drivers/openvision/openvision.ko |grep layout
0xd7e8ad31      module_layout
```

**Comment by petrkr** [comment]
@persianpros is possible to see dir listing of all possible drivers at that SRC URL? There is 403 Forbidden on dir listing.

**Comment by persianpros** [comment]
No as that is not our server and they disabled it.

**Comment by petrkr** [comment]
There must be something different on kernel build side. All three (based on history of file sf4008.bb) version has same module_layout pattern... 

Also first two are exactly same, zip file is newer, .ko file also, but checksum is same.

```
[petrkr@pkdell openvision]$ modprobe --dump-modversions linuxtv.ko |grep layout
0xe39910bb      module_layout
[petrkr@pkdell openvision]$ modprobe --dump-modversions linuxtv2.ko |grep layout
0xe39910bb      module_layout
[petrkr@pkdell openvision]$ modprobe --dump-modversions linuxtv3.ko |grep layout
0xe39910bb      module_layout
[petrkr@pkdell openvision]$ md5sum linuxtv.ko linuxtv2.ko linuxtv3.ko 
616aa55ebb077a9a543aad982664cfd5  linuxtv.ko
616aa55ebb077a9a543aad982664cfd5  linuxtv2.ko
0f119e86b900b02394a1ee9811be8c92  linuxtv3.ko
```
```
-rw-r--r-- 1 petrkr users 4514889 Jun  9  2019 sf4008-drivers-4.1.37-6.3.0-20180107.zip --> linuxtv.ko
-rw-r--r-- 1 petrkr users 4495447 Jun  9  2019 sf4008-drivers-4.1.37-6.3.0-20180328.zip --> linuxtv2.ko
-rw-r--r-- 1 petrkr users 4484070 Jun  9  2019 sf4008-drivers-4.1.37-6.3.0-20181015.zip --> linuxtv3.ko
```

**Comment by petrkr** [comment]
Find out, this is that commit, which breaks kernel module layouts, so it makes impossible to load linuxtv.ko (due different module_layout)

Now let's do research which option that changes

https://github.com/OpenVisionE2/meta-octagon/commit/ece23a0b8f74c53dab765565a35cab98d3df653d#diff-5eb50de2b24cb40b802ec2b935e023c0

**Comment by persianpros** [comment]
Try CONFIG_FUSE_FS from m to y and let me know :+1:

**Comment by petrkr** [comment]
Already rebuilt with this
```
-# CONFIG_ROOT_NFS is not set
+CONFIG_ROOT_NFS=y
 # CONFIG_NFS_FSCACHE is not set
 # CONFIG_NFS_USE_LEGACY_DNS is not set
 CONFIG_NFS_USE_KERNEL_DNS=y
-CONFIG_NFSD=m
+CONFIG_NFSD=y
 CONFIG_NFSD_V3=y
 # CONFIG_NFSD_V3_ACL is not set
-CONFIG_NFSD_V4=y
+#CONFIG_NFSD_V4=y
 CONFIG_GRACE_PERIOD=y
```

and result is right module_layout.. so it's some of those NFS options...

`builder@builder-VirtualBox:~/openvision-development-platform/build/tmp/work/sf4008-oe-linux-gnueabi/linux-octagon/4.1.37-openvision/build/fs/cifs$ modprobe --dump-modversions ./cifs.ko  |grep lay
0xe39910bb	module_layout
```

unluckly my environment gets broken on this now :(

```
| ../git/configure: line 21778: syntax error near unexpected token `fi'
| ../git/configure: line 21778: `fi'
| WARNING: /home/builder/openvision-development-platform/build/tmp/work/sf4008-oe-linux-gnueabi/enigma2/develop+gitAUTOINC+b9afa0a05b-r0/temp/run.do_configure.5401:1 exit 1 from 'exit 1'
```

**Comment by persianpros** [comment]
Can you just try CONFIG_FUSE_FS=y and don't change anything else? I want to be sure of something ...

**Comment by petrkr** [comment]
On latest tree? Ok I will try do after free compiler on this try.

**Comment by petrkr** [comment]
> Can you just try CONFIG_FUSE_FS=y and don't change anything else? I want to be sure of something ...


This change not change `module_layout` at all. Still same as before.  But regarding to my test before it seems it caused that support for NFSD_v4, retrying now.

**Comment by persianpros** [comment]
I'm not talking about module_layout, some models require CONFIG_FUSE_FS to boot that's what I want to be sure about this model ;)

**Comment by petrkr** [comment]
> I'm not talking about module_layout, some models require CONFIG_FUSE_FS to boot that's what I want to be sure about this model ;)

I see, but this one is caused kernel can not load linuxtv.ko because of different module_layout, changing FUSE from module to built-in will not solve different version of binary blob module with custom built kernel

**Comment by petrkr** [comment]
Now I must find out how to de-brick this image and load flash one,, I really do not want disassemble receiver to disconnect hard-drive :D

**Comment by persianpros** [comment]
But if this is the case then we need to change almost all defconfig files, this is why enigma2 STBs are not really open source because they have pre-compiled .ko files.

**Comment by petrkr** [comment]
> But if this is the case then we need to change almost all defconfig files, this is why enigma2 STBs are not really open source because they have pre-compiled .ko files.

yes, hate those closed sources kernel files.. That would keep you stuck on exact kernel and gcc version and mostly configuration too...

Not talking about impossible to do bugfixes on kernel and most of those linux receiver are connected to internet.

Can be good to have some check during building like "expected" version of something to determine if such configuration is still compatible with binary `.ko` modules, it would help catch those missconfiguriations more early

**Comment by petrkr** [comment]
Ha, finally...

So I can say, if you remove just NFSD4, then it boot up

```
root@sf4008:~# lsmod
Module                  Size  Used by
nfsd                   79201  11
ipv6                  285240  56
openvision              1243  0
linuxtv              8822612  6
fuse                   72883  1
```

```
root@sf4008:~# ps  |grep enig
 1584 root      2648 S    {enigma2.sh} /bin/sh /usr/bin/enigma2.sh
 1593 root      129m S    /usr/bin/enigma2
```

**Comment by petrkr** [comment]
```
diff --git a/recipes-bsp/linux/linux-octagon-4.1.37/defconfig b/recipes-bsp/linux/linux-octagon-4.1.37/defconfig
index f1f2160..88bc38f 100644
--- a/recipes-bsp/linux/linux-octagon-4.1.37/defconfig
+++ b/recipes-bsp/linux/linux-octagon-4.1.37/defconfig
@@ -3799,7 +3799,7 @@ CONFIG_NFS_USE_KERNEL_DNS=y
 CONFIG_NFSD=m
 CONFIG_NFSD_V3=y
 # CONFIG_NFSD_V3_ACL is not set
-CONFIG_NFSD_V4=y
+#CONFIG_NFSD_V4=y
 CONFIG_GRACE_PERIOD=y
 CONFIG_LOCKD=y
 CONFIG_LOCKD_V4=y

```

**Comment by persianpros** [comment]
Ok let me apply this for all :+1:

**Comment by petrkr** [comment]
Now I am at "progress wizard"...  what should be there ? It is at like 2% progress

**Comment by petrkr** [comment]
Aha, I should press "OK".. maybe  good idea do some big text with simething like "PRESS OK to continue" :) as other screens has something at that middle of screen and this was empty and I waiting what will appear

**Comment by persianpros** [comment]
Done, all defconfig files changed and pushed :+1: 

I think we can close this issue thanks to you :1st_place_medal:
