### ISSUE TITLE
build faild!!!!¡

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-development-platform#30]
ERROR: Execution of '/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/temp/run.do_compile.9742' failed with exit code 1:
| [1/136] sh4-oe-linux-gcc -ml -m4 --sysroot=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot  -o tests/check/elements_rtph263 'tests/check/7d01337@@elements_rtph263@exe/elements_rtph263.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--start-group -lm /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstreamer-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgobject-2.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libglib-2.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstbase-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstnet-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgio-2.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstcheck-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstaudio-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstvideo-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstpbutils-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstrtp-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstrtsp-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstsdp-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgsttag-1.0.so /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/libgstapp-1.0.so -Wl,--end-group
| [2/136] sh4-oe-linux-gcc -ml -m4 --sysroot=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot -Itests/check/7d01337@@elements_rtpbin@exe -Itests/check -I../git/tests/check -I. -I../git/ -I../git/gst-libs -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/gstreamer-1.0 -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/libmount -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/blkid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -fvisibility=hidden -fno-strict-aliasing -DG_DISABLE_DEPRECATED -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Winit-self -Wmissing-include-dirs -Wno-multichar -Wvla -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -Wold-style-definition -Waggregate-return -O2 -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0=/usr/src/debug/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0 -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot= -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot-native= -pthread -DHAVE_CONFIG_H=1 -UG_DISABLE_ASSERT -UG_DISABLE_CAST_CHECKS '-DGST_CHECK_TEST_ENVIRONMENT_BEACON="GST_PLUGIN_LOADING_WHITELIST"' '-DGST_TEST_FILES_PATH="/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/git/tests/check/../files"' -DGST_USE_UNSTABLE_API -MD -MQ 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o' -MF 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o.d' -o 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o' -c ../git/tests/check/elements/rtpbin.c
| FAILED: tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o
| sh4-oe-linux-gcc -ml -m4 --sysroot=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot -Itests/check/7d01337@@elements_rtpbin@exe -Itests/check -I../git/tests/check -I. -I../git/ -I../git/gst-libs -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/gstreamer-1.0 -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/libmount -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/blkid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -fvisibility=hidden -fno-strict-aliasing -DG_DISABLE_DEPRECATED -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Winit-self -Wmissing-include-dirs -Wno-multichar -Wvla -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -Wold-style-definition -Waggregate-return -O2 -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0=/usr/src/debug/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0 -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot= -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot-native= -pthread -DHAVE_CONFIG_H=1 -UG_DISABLE_ASSERT -UG_DISABLE_CAST_CHECKS '-DGST_CHECK_TEST_ENVIRONMENT_BEACON="GST_PLUGIN_LOADING_WHITELIST"' '-DGST_TEST_FILES_PATH="/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/git/tests/check/../files"' -DGST_USE_UNSTABLE_API -MD -MQ 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o' -MF 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o.d' -o 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o' -c ../git/tests/check/elements/rtpbin.c
| ../git/tests/check/elements/rtpbin.c: In function 'test_quick_shutdown':
| ../git/tests/check/elements/rtpbin.c:942:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
|    for (guint r = 0; r < 1000; r++) {
|    ^
| ../git/tests/check/elements/rtpbin.c:942:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
| [3/136] sh4-oe-linux-gcc -ml -m4 --sysroot=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot -Itests/check/7d01337@@elements_rtph264@exe -Itests/check -I../git/tests/check -I. -I../git/ -I../git/gst-libs -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/inclDISABLE_CAST_CHECKS '-DGST_CHECK_TEST_ENVIRONMENT_BEACON="GST_PLUGIN_LOADING_WHITELIST"' '-DGST_TEST_FILES_PATH="/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/git/tests/check/../files"' -DGST_USE_UNSTABLE_API -MD -MQ 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o' -MF 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o.d' -o 'tests/check/7d01337@@elements_rtpbin@exe/elements_rtpbin.c.o' -c ../git/tests/check/elements/rtpbin.c                                                                           | ../git/tests/check/elements/rtpbin.c: In function 'test_quick_shutdown':   | ../git/tests/check/elements/rtpbin.c:942:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode                                  |    for (guint r = 0; r < 1000; r++) {                                      |    ^                                                                       | ../git/tests/check/elements/rtpbin.c:942:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code                          | [3/136] sh4-oe-linux-gcc -ml -m4 --sysroot=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot -Itests/check/7d01337@@elements_rtph264@exe -Itests/check -I../git/tests/check -I. -I../git/ -I../git/gst-libs -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/gstreamer-1.0 -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/libmount -I/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot/usr/include/blkid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -fvisibility=hidden -fno-strict-aliasing -DG_DISABLE_DEPRECATED -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Winit-self -Wmissing-include-dirs -Wno-multichar -Wvla -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -Wold-style-definition -Waggregate-return -O2 -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0=/usr/src/debug/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0 -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot= -fdebug-prefix-map=/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/recipe-sysroot-native= -pthread -DHAVE_CONFIG_H=1 -UG_DISABLE_ASSERT -UG_DISABLE_CAST_CHECKS '-DGST_CHECK_TEST_ENVIRONMENT_BEACON="GST_PLUGIN_LOADING_WHITELIST"' '-DGST_TEST_FILES_PATH="/home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/gstreamer1.0-plugins-good/1.17.0.1+gitAUTOINC+d6961235e8-r0/git/tests/check/../files"' -DGST_USE_UNSTABLE_API -MD -MQ 'tests/check/7d01337@@elements_rtph264@exe/elements_rtph264.c.o' -MF 'tests/check/7d01337@@elements_rtph264@exe/elements_rtph264.c.o.d' -o 'tests/check/7d01337@@elements_rtph264@exe/elements_rtph264.c.o' -c ../git/tests/check/elements/rtph264.c
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
|
ERROR: Task (/home/ubuntu/openvision-development-platform/meta-openvision/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5869 tasks of which 5592 didn't need to be rerun and 1 failed.

**Comment by persianpros** [comment]
Update via update.sh, it's ok now.
