### ISSUE TITLE
openvision 9.3 spark build failed

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-development-platform#32]
WARNING: linux-sh4-spark-2.6.32.71-stm24-0217-openvision do_package_qa: QA Issue: linux-sh4-spark: SRC_URI uses unstable GitHub archives [src-uri-bad]    ERROR: fp-control-1.1+gitAUTOINC+39d6a94db2-r0 do_patch: Command Error: 'quilt --quiltrc /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/1.1+gitAUTOINC+39d6a94db2-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:                                            Applying patch spark_fp-control.patch                                        patching file autogen.sh
patching file configure.ac
patching file fp_control.c
Hunk #7 FAILED at 437.
1 out of 7 hunks FAILED -- rejects in file fp_control.c
patching file global.c
patching file global.h
patching file Makefile.am
patching file Spark.c
patching file Spark.h
Patch spark_fp-control.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /home/ubuntu/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/1.1+gitAUTOINC+39d6a94db2-r0/temp/log.do_patch.30275
ERROR: Task (/home/ubuntu/openvision-development-platform/meta-sh4/recipes-bsp/extra/fp-control_git.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6766 tasks of which 6187 didn't need to be rerun and 1 failed.                                                             
Summary: 1 task failed:
  /home/ubuntu/openvision-development-platform/meta-sh4/recipes-bsp/extra/fp-control_git.bb:do_patch
Summary: There were 25 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:102: recipe for target 'image' failed
make: *** [image] Error 1

Done, the compiled image is in build/tmp/deploy/images/spark folder!
It's a zipped file like openvision-enigma2-develop-multilanguage-9.3-r81-spark.zip
ubuntu@ip-172-31-26-148:~/openvision-development-platform$

**Comment by persianpros** [comment]
Patch should be updated as sh4-apps updated ...

**Comment by ahmedmoselhi** [comment]
> Patch should be updated as sh4-apps updated ...

i ran update.sh before compile.. is this enough or i should run clean build

**Comment by persianpros** [comment]
No we should update the patch and currently I don't have the time for it.

**Comment by ahmedmoselhi** [comment]
> No we should update the patch and currently I don't have the time for it.

sad... will wait then till it got updated
