### ISSUE TITLE
Incorrect Download-URL in meta-edision\recipes-bsp\drivers\os-dvb-modules-osmini.bb + os-dvb-modules.inc

### ISSUE THREAD

**Issue by WXbet** [OpenVisionE2/openvision-development-platform#33]
ERROR: os-dvb-modules-osmini-4.11+20171106-r0 do_fetch: Fetcher failure for URL: 'https://github.com/edision-open/edision-driver/releases/download/20171106/osmini-drivers-4.11-20171106.zip'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /opt/OpenVisionE2/openvision-development-platform/build/tmp/work/osmini-oe-linux/os-dvb-modules-osmini/4.11+20171106-r0/temp/log.do_fetch.2346
ERROR: Task (/opt/OpenVisionE2/openvision-development-platform/meta-edision/recipes-bsp/drivers/os-dvb-modules-osmini.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6191 tasks of which 5504 didn't need to be rerun and 1 failed.

Recipe generated URL: https://github.com/edision-open/edision-driver/releases/download/20171106/osmini-drivers-4.11-20171106.zip
Correct URL: https://github.com/edision-open/edision-driver/releases/download/20171106/osmini-drivers-4.11.0-20171106.zip

Something is wrong with the KV variable in os-dvb-modules.inc.

**Comment by persianpros** [comment]
Thanks for the report, I'm working on it and the update will be ready in next 20 minutes :+1:
