### ISSUE TITLE
build failed for vusolo

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/openvision-development-platform#34]
DEBUG: Executing shell function do_compile
NOTE: make -j 8 HOSTCC=gcc  -isystem/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/include -march=native          -O2 -pipe -L/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/lib                         -L/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/lib                         -Wl,-rpath,/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/lib                         -Wl,-O1 HOSTCPP=gcc  -E vmlinux CC=mipsel-oe-linux-gcc  -fuse-ld=bfd -fdebug-prefix-map=/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision=/usr/src/debug/linux-vuplus/3.9.6-openvision                      -fdebug-prefix-map=/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot=                      -fdebug-prefix-map=/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native=  -fdebug-prefix-map=/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source=/usr/src/kernel   LD=mipsel-oe-linux-ld.bfd 
  GEN     /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
scripts/kconfig/conf --silentoldconfig Kconfig
  GEN     /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
  WRAP    arch/mips/include/generated/asm/trace_clock.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  Using /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source as source for kernel
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/empty.o
  CC      scripts/mod/devicetable-offsets.s
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:64:1: warning: 'succeed_file' defined but not used [-Wunused-function]
 succeed_file(void)
 ^~~~~~~~~~~~
In file included from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler.h:54,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/stddef.h:1,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/stddef.h:4,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/posix_types.h:4,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/types.h:13,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/types.h:5,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/mod_devicetable.h:11,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/devicetable-offsets.c:2:
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler-gcc.h:103:1: fatal error: linux/compiler-gcc9.h: No such file or directory
  103 | #include gcc_header(__GNUC__)
      | ^~~~
compilation terminated.
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/Makefile:34: recipe for target 'scripts/mod/devicetable-offsets.s' failed
make[4]: *** [scripts/mod/devicetable-offsets.s] Error 1
make[4]: *** Waiting for unfinished jobs....
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/Makefile.build:454: recipe for target 'scripts/mod' failed
make[3]: *** [scripts/mod] Error 2
make[3]: *** Waiting for unfinished jobs....
In file included from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:162:0:
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c: In function 'main':
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  int relocs_size;
      ^~~~~~~~~~~
In file included from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:160:0:
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  int relocs_size;
      ^~~~~~~~~~~
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/Makefile:518: recipe for target 'scripts' failed
make[2]: *** [scripts] Error 2
Makefile:130: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: oe_runmake failed
WARNING: /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.44695:1 exit 1 from 'exit 1'
ERROR: Execution of '/home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.44695' failed with exit code 1:
  GEN     /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
scripts/kconfig/conf --silentoldconfig Kconfig
  GEN     /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
  WRAP    arch/mips/include/generated/asm/trace_clock.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  Using /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source as source for kernel
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/empty.o
  CC      scripts/mod/devicetable-offsets.s
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:64:1: warning: 'succeed_file' defined but not used [-Wunused-function]
 succeed_file(void)
 ^~~~~~~~~~~~
In file included from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler.h:54,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/stddef.h:1,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/stddef.h:4,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/posix_types.h:4,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/types.h:13,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/types.h:5,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/mod_devicetable.h:11,
                 from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/devicetable-offsets.c:2:
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler-gcc.h:103:1: fatal error: linux/compiler-gcc9.h: No such file or directory
  103 | #include gcc_header(__GNUC__)
      | ^~~~
compilation terminated.
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/Makefile:34: recipe for target 'scripts/mod/devicetable-offsets.s' failed
make[4]: *** [scripts/mod/devicetable-offsets.s] Error 1
make[4]: *** Waiting for unfinished jobs....
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/Makefile.build:454: recipe for target 'scripts/mod' failed
make[3]: *** [scripts/mod] Error 2
make[3]: *** Waiting for unfinished jobs....
In file included from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:162:0:
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c: In function 'main':
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  int relocs_size;
      ^~~~~~~~~~~
In file included from /home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:160:0:
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  int relocs_size;
      ^~~~~~~~~~~
/home/openvisionbuild/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/Makefile:518: recipe for target 'scripts' failed
make[2]: *** [scripts] Error 2
Makefile:130: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2
WARNING: /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.44695:1 exit 1 from 'exit 1'

**Comment by Hains** [comment]
Update openvision-development-platform, vusolo build should be OK now.
https://github.com/OpenVisionE2/meta-vuplus/commit/68ce20c7dcc0d197998ce8352d47543fba32b073

**Comment by ziko-ZR1** [comment]
Thanks but the update didn't include the makefile disable warnings 
WARNING: linux-vuplus-3.9.6-openvision do_fetch: Failed to fetch URL file://0006-makefile-disable-warnings.patch, attempting MIRRORS if available
ERROR: linux-vuplus-3.9.6-openvision do_fetch: Fetcher failure: Unable to find file file://0006-makefile-disable-warnings.patch anywhere. The paths that were searched were:
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/openvision
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/openvision
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/openvision
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/vusolo
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/vusolo
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/vusolo
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/mipsarcho32el
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/mipsarcho32el
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/mipsarcho32el
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/mipsarcho32
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/mipsarcho32
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/mipsarcho32
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/mipsarchel
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/mipsarchel
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/mipsarchel
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/mipsarch
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/mipsarch
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/mipsarch
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/mipsel
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/mipsel
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/mipsel
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus-3.9.6/
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus/
    /home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/files/
    /home/ziko/enigma2/build/sources
ERROR: linux-vuplus-3.9.6-openvision do_fetch: Fetcher failure for URL: 'file://0006-makefile-disable-warnings.patch'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/log.do_fetch.4155
ERROR: Task (/home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus_3.9.6.bb:do_fetch) failed with exit code '1'

**Comment by Hains** [comment]
Yeah wrong patch filename..
Update and try again.

**Comment by ziko-ZR1** [comment]
Thanks for your work , i got an error again

ERROR: linux-vuplus-3.9.6-openvision do_patch: Command Error: 'quilt --quiltrc /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0005-uaccess-dont-mark-register-as-const.patch
patching file arch/arm/include/asm/uaccess.h
Hunk #1 FAILED at 172.
1 out of 1 hunk FAILED -- rejects in file arch/arm/include/asm/uaccess.h
Patch 0005-uaccess-dont-mark-register-as-const.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /home/openvisionbuild/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/log.do_patch.4707
ERROR: Task (/home/openvisionbuild/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus_3.9.6.bb:do_patch) failed with exit code '1'

**Comment by persianpros** [comment]
I will close this as it's not ready yet, instead of trying and trying give me some time to check this meta and kernel 3.9.6
