### ISSUE TITLE
cifs share mount problem

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/openvision-development-platform#34]
**Open Vision revision**
Tell us it's OV 10.1-rx?
ov 10.1 r205
**STB name**

sf8008

**smallflash/middleflash**

enough flash

**Logs**

'//192.168.1.21/e' /media/net/e
mount: mounting //192.168.1.21/e on /media/net/e failed: No such device

**Describe the bug**
i can't mount my drive using cifs share , but it works very well in openatv with the same drive

**Screenshots**

![1_0_1_70A_32C8_13E_820000_0_0_0_20200812173616](https://user-images.githubusercontent.com/43075184/90044024-ef04ee80-dcc4-11ea-9433-ecdadd051e1f.jpg)

![1_0_1_70A_32C8_13E_820000_0_0_0_20200812173512](https://user-images.githubusercontent.com/43075184/90044030-f3310c00-dcc4-11ea-8b4b-9c4d3e9d4c0b.jpg)

here is some screenshots from openatv 

![screenshot_20200812180915](https://user-images.githubusercontent.com/43075184/90045479-01802780-dcc7-11ea-94f0-f8e8c678c283.jpg)

![screenshot_20200812180937](https://user-images.githubusercontent.com/43075184/90045522-11980700-dcc7-11ea-9b68-15079dc13454.jpg)

**Comment by persianpros** [comment]
is kernel-module-cifs installed?

**Comment by ziko-ZR1** [comment]
> Is kernel-module-cifs installed?

yes

**Comment by persianpros** [comment]
What about "cifs-utils"?

**Comment by ziko-ZR1** [comment]
> What about "cifs-utils"?

both packages are installed

![Screenshot from 2020-08-14 16-13-09](https://user-images.githubusercontent.com/43075184/90272926-a9bff880-de4d-11ea-9f3d-e195c9ea75d3.png)

![1_0_19_22D2_434_1_C00000_0_0_0_20200814174651](https://user-images.githubusercontent.com/43075184/90273006-c5c39a00-de4d-11ea-87f7-5538ba532bab.jpg)

**Comment by kueken** [comment]
Mount-options->
Your cifs share probably needs a version.
You can compare it to the setting in the ATV.
There is not only rw.
Is not a bug of the image

**Comment by ziko-ZR1** [comment]
> Mount-options->
> Your cifs share probably needs a version.
> You can compare it to the setting in the ATV.
> There is not only rw.
> Is not a bug of the image

it works with pli also without those extra options

![1_0_19_143A_3B6_110_DDE0000_0_0_0_20200818110537](https://user-images.githubusercontent.com/43075184/90500487-dc663b80-e142-11ea-867e-a50e621442f5.jpg)

![1_0_19_143A_3B6_110_DDE0000_0_0_0_20200818110553](https://user-images.githubusercontent.com/43075184/90500494-e0925900-e142-11ea-9c9f-34082345e4d4.jpg)

**Comment by kueken** [comment]
I don't know your cifs share, but trying
'vers = 1.0'
Can only guess why it doesn't work.

**Comment by ziko-ZR1** [comment]
> I don't know your cifs share, but trying
> 'vers = 1.0'
> Can only guess why it doesn't work.


![1_0_19_143A_3B6_110_DDE0000_0_0_0_20200818115415](https://user-images.githubusercontent.com/43075184/90504925-b42e0b00-e149-11ea-8d08-5b4e9d3af8c2.jpg)

![1_0_19_143A_3B6_110_DDE0000_0_0_0_20200818115433](https://user-images.githubusercontent.com/43075184/90504935-b7c19200-e149-11ea-83eb-e0eba6d97703.jpg)

**Comment by kueken** [comment]
have no more idea.
I don't understand it either, in principle it works the same as in other images.
There is also no negative feedback in the forum and cifs-Share is certainly used very often.
I can't say much about the sf8008.

**Comment by ziko-ZR1** [comment]
> have no more idea.
> I don't understand it either, in principle it works the same as in other images.
> There is also no negative feedback in the forum and cifs-Share is certainly used very often.
> I can't say much about the sf8008.

this problem also exists on my vu solo

**Comment by kueken** [comment]
I would guess what doesn't fit in defconfig.
Please try a local construction by taking over the defconfig from pli, or OE-Core and then report.
https://github.com/zhtq/meta-octagon/blob/master/recipes-linux/linux-octagon-4.4.35/sf8008/defconfig

**Comment by petrkr** [comment]
Defconfig is kernel related, this problem is NOT kernel related. It's because windows has disabled SMBv1 and both smbclient v 3.6 and netscan plugin in networkbrowser uses old SMBv1 protocol.

Here are two issues in one actually
1) can not mount without vers
2) network browser does not work

**Comment by kueken** [comment]
That is not right.

With Samba version 3.6.25 you can address all protocols in the same way as you can with Samba version 4.
Unfortunately, this is always mixed up.

**Comment by petrkr** [comment]
regarding to documentation, only SMB2
`https://wiki.samba.org/index.php/Samba_3.6_Features_added/changed#SMB2_support`

SMB3 was added around version 4 `https://www.samba.org/samba/history/samba-4.1.0.html`

Anyway what is reason to keep using deprecated 3.x version? As version 3.6 got discontinued 5 years ago already !
`https://wiki.samba.org/index.php/Samba_Release_Planning#Discontinued`

**Comment by kueken** [comment]
Incidentally, you can still reactivate version smb 1 in every Windows.
It's just Microsoft that disabled it.
The reasons for this are somewhat questionable.
Samba and security is a questionable thing no matter which version.
It is the desire to have access in the local network and that as simple as possible.
Now it is made unnecessarily (typically micorosoft) complicated.
With a fairly high degree of certainty, this leads to completely open networks rather than doing anything.
But you want Windows network, so I would advise you to do the test.
A defconfig changes a lot with regard to the things required.
But you are also welcome to build with Samba 4 if you already know everything better and don't do it.
There are good reasons for Samba 3, you will find that out when you build the current version Samba 4.
Believe me it will take very long time for nothing better

**Comment by petrkr** [comment]
Tested kernel module cifs. That works fine with version 2 and 3:

Vers 1, expected to not work.
```
root@sf4008:/mnt# mount.cifs //10.200.0.130/Multimedia /mnt/a -o username=petrkr,vers=1.0
Password for petrkr@//10.200.0.130/Multimedia: 
mount error: Server abruptly closed the connection.
This can happen if the server does not support the SMB version you are trying to use.
The default SMB version recently changed from SMB1 to SMB2.1 and above. Try mounting with vers=1.0.
```

vers 2 and 3:
```
root@sf4008:/mnt# mount.cifs //10.200.0.130/Multimedia /mnt/a -o username=petrkr,vers=2.0
Password for petrkr@//10.200.0.130/Multimedia: 
root@sf4008:/mnt# ls a
PINK FLOYD - PILSE (2 DVD)
umonut a
```

```
root@sf4008:/mnt# mount.cifs //10.200.0.130/Multimedia /mnt/a -o username=petrkr,vers=3.0
Password for petrkr@//10.200.0.130/Multimedia: 
root@sf4008:/mnt# ls a
PINK FLOYD - PILSE (2 DVD)
```

both works as expected.
but smbclient does not.

I can try it, but need to understand how better debug BitBake build system than rebuild everything and wait long time to parse things. How to run builds by hand. This kind of testing is really uncomfortable. Maybe you can get some hint how to do customs builds of custom software by specifiing root and gcc / glibc manually (as I did loong time ago with UBNT SDK)

**Comment by kueken** [comment]
You are currently changing your receiver and so testing and looking for errors makes no sense.
The sf4008 has nothing to do with the previously mentioned sf8008.

That does not work like this

**Comment by petrkr** [comment]
Because I do not have sf8008, but built packages are same. At kernel I can see different between 4 and 8 at that smb311=y

SMB2 at sf4008
https://github.com/OpenVisionE2/meta-octagon/blob/cab9829895141538b74620744d1fc4797069ca69/recipes-bsp/linux/linux-octagon-4.1.37/defconfig#L3822

https://github.com/OpenVisionE2/meta-octagon/blob/cab9829895141538b74620744d1fc4797069ca69/recipes-bsp/linux/linux-octagon-4.9.51/defconfig#L3938

in 14 days I will test if that `CONFIG_CIFS_SMB311=y` option not breaking it out.

**Comment by petrkr** [comment]
actually all of my command line tests can @ziko-ZR1 test on his sf8008 aswell and post if that works or does not works for him. I just posting how I tested it and what was output of those tests...

Now he can try it on his box.

**Comment by persianpros** [comment]
As I don't use windows for years I don't care about windows related things and that's why samba removed from the build to reduce the image size and compile time.

**Comment by petrkr** [comment]
Hmm I can not test it already from pub over VPN.. So I will test it whenever will get time at home again...

Also I do not focus on windows related thigs.. But since I like to help, I will try to debug even those problems, because lot of users are NOT linux friendly at all...

For my octagon I use NFS shares from linux based server. So even for me cifs is only "nice 2 have" if need to play something from Win 10 which I have to use just because of VR.

**Comment by kueken** [comment]
Because of comparing the different defconfig of different receivers ....
We all don't know what is activated and added via closed source drivers.
Therefore it is difficult to compare.
I would therefore simply test the defconfig from pli, because this is issued by the manufacturer himself as a basis.
Just try it

**Comment by WanWizard** [comment]
> Well after debug network and source codes, problem is somewhere in this OpenPLI's C library https://github.com/OpenPLi/enigma2-plugins/blob/master/networkbrowser/src/lib/smbinfo.c

Your Wireshark trace is about NetBIOS, on port 139. Modern Windows (and Samba) servers don't use 139 anymore, they talk CIFS over 445. So very logical you get an RST, there is nothing listening on that port.

I've jjust tested the network browser on my SF8008, it has no issues finding everything on my LAN that talks CIFS. My NAS doesn't have NetBIOS active, only CIFS on 445, and no problem detecting its shares, and not hangups...

**Comment by petrkr** [comment]
> > Well after debug network and source codes, problem is somewhere in this OpenPLI's C library https://github.com/OpenPLi/enigma2-plugins/blob/master/networkbrowser/src/lib/smbinfo.c
> 
> Your Wireshark trace is about NetBIOS, on port 139. Modern Windows (and Samba) servers don't use 139 anymore, they talk CIFS over 445. So very logical you get an RST, there is nothing listening on that port.
> 
> I've jjust tested the network browser on my SF8008, it has no issues finding everything on my LAN that talks CIFS. My NAS doesn't have NetBIOS active, only CIFS on 445, and no problem detecting its shares, and not hangups...

https://github.com/OpenPLi/enigma2-plugins/blob/master/networkbrowser/src/lib/smbinfo.c#L139

can you please show me where this library use port 445 ? I can not see that in code. So if you using OpenPLI's NetworkBrowser (not OpenVisions's) which uses this .so library. Then your cifs must listen on 139 as well.. Can you place tcpdump that too?

**Comment by WanWizard** [comment]
Did I say that? 

smbinfo is for old netbios connections only. If 139 is not open, open_sockets() will fail and it will be skipped.

Your statement is that that would hang the box, and I just told you my SF8008 doesn't, as my NAS doesn't have 139 open at all, and it still lists the available shares just fine.

**Comment by petrkr** [comment]
> Did I say that?
> 
> smbinfo is for old netbios connections only. If 139 is not open, open_sockets() will fail and it will be skipped.
> 
> Your statement is that that would hang the box, and I just told you my SF8008 doesn't, as my NAS doesn't have 139 open at all, and it still lists the available shares just fine (after entering username/password, anonymous enumeration is disabled since SMBv2).

Ok I understand. So then where is that part of code, which will do discover on new protocol on port 445?
https://github.com/OpenPLi/enigma2-plugins/blob/master/networkbrowser/src/NetworkBrowser.py#L221

I just trying understand that code to do some debug on it.

**Comment by WanWizard** [comment]
Afaik it doesn't do any enumeration over 445, that code is as old as methuselah.

I just commented on your remark your box hangs on 139 discovery.

**Comment by WanWizard** [comment]
It should probably use the WS-Discovery library for CIFS discovery, this is the mechanism Windows uses too. But I'm not a developer.

**Comment by ziko-ZR1** [comment]
> > Did I say that?
> > smbinfo is for old netbios connections only. If 139 is not open, open_sockets() will fail and it will be skipped.
> > Your statement is that that would hang the box, and I just told you my SF8008 doesn't, as my NAS doesn't have 139 open at all, and it still lists the available shares just fine (after entering username/password, anonymous enumeration is disabled since SMBv2).
> 
> Ok I understand. So then where is that part of code, which will do discover on new protocol on port 445?
> https://github.com/OpenPLi/enigma2-plugins/blob/master/networkbrowser/src/NetworkBrowser.py#L221
> 
> I just trying understand that code to do some debug on it.

what you want me to test on my receiver  ? so i can help with the logs
give me the whole commands you want me to try

**Comment by petrkr** [comment]
> It should probably use the WS-Discovery library for CIFS discovery, this is the mechanism Windows uses too. But I'm not a developer.

I see.
WS Library seems to be for WebServices (SOAP based with WSDL). Regadring to documentation https://python-ws-discovery.readthedocs.io/en/latest/

Well I can check how do it other way also how to fix that C library (or if will deprecated it anymore)... There is new code in OpenVision's repository based on `smbclient` call, but still is built that openvision's one. 

Also since this is enigma - python plugin, it's box-independent as all code is same for all platforms. (Maybe just other box will include that OV's one instead OpenPLI one) but that must confirm @persianpros for example... I saw some commit which fallback few plugins to OpenPLI (epg, networkbrowser...)

**Comment by petrkr** [comment]
> > > Did I say that?
> > > smbinfo is for old netbios connections only. If 139 is not open, open_sockets() will fail and it will be skipped.
> > > Your statement is that that would hang the box, and I just told you my SF8008 doesn't, as my NAS doesn't have 139 open at all, and it still lists the available shares just fine (after entering username/password, anonymous enumeration is disabled since SMBv2).
> > 
> > 
> > Ok I understand. So then where is that part of code, which will do discover on new protocol on port 445?
> > https://github.com/OpenPLi/enigma2-plugins/blob/master/networkbrowser/src/NetworkBrowser.py#L221
> > I just trying understand that code to do some debug on it.
> 
> what you want me to test on my receiver ? so i can help with the logs
> give me the whole commands you want me to try

For first try that smbclient if works as expected:

`smbclient -m SMB3 -g -U username -L 1.2.3.4` change 1.2.3.4 for your IP and username for your username. you can also try change SMB3 to SMB2

in this test we want try if your box with smbclient is able to cumunicate on SMB2 (or 3) protocol.

then you can try mount (to test CIFS kernel module)
`mkdir /mnt/a`
`mount.cifs //1.2.3.4/ShareName /mnt/a -o username=username,vers=2.0`

again change IP, share name and username.

In this test I suppose you have disabled SMBv1 in Windows 10 and enabled SMB2 and 3 (regading that post from @persianpros earlier)


for my box sf4008
smbclient does not work (only SMBv1 supported)
mount.cifs works (vers 2,3) with SMBv1 disabled of course

**Comment by WanWizard** [comment]
Ideally the entire network browser should be rewritten, parts of its code is 15 years old, from long before CIFS even existed.

**Comment by petrkr** [comment]
> Ideally the entire network browser should be rewritten, parts of its code is 15 years old, from long before CIFS even existed.

Yes agree, better than fix 15y old code to support deprecated things, better to write already new one with actual things... Question is if still support old NAS boxes / routers which runs old samba servers or not. I preffer to not.

**Comment by WanWizard** [comment]
I don't see why not. There are plenty of implementations that still require SMBv1, it should be up to the user whether or not they use it. I have enabled it on my NAS for example, because my MFC only does v1 as destination for scanning...

**Comment by ziko-ZR1** [comment]
> mount.cifs

the drive is mounted now with your command : `mount.cifs //1.2.3.4/ShareName /mnt/a -o username=username,vers=2.0`

![Capture](https://user-images.githubusercontent.com/43075184/91047069-67e33f00-e611-11ea-8da9-79cdd067fedb.PNG)

![1_0_1_28_2_212C_1860000_0_0_0_20200821190851](https://user-images.githubusercontent.com/43075184/91047080-6c0f5c80-e611-11ea-88bb-c91d31ff2758.jpg)

**Comment by petrkr** [comment]
So CIFS mount works on SMBv2 protocol. Cool. what about that SMB client ? Does it work? For me it communicate only by SMBv1 and I can not force it to SMBv2 even I use `-m SMB2`. But maybe different settings on kernel can help as @kueken mention before.

I still think Samba daemon / helpers are totally separated from kernel cifs module, but let's try that to be sure. Also check version of `smbclient -v` if it's 3.x or 4.x. I saw already some BB classes for 4.x but do not know if they are in use

**Comment by petrkr** [comment]
Anyway I found project `pysmb` it's experimental, so using with caution. But it's already in opkg repository of OpenVision's images. I tested browse for one mine W10 machine (still same) and it working on SMBv2 protocol. So maybe it's good idea to do Share Discover by that plugin.

You can try that too directly from python console:
1) make sure package is installed `python-pysmb`
2) python

in python console write:
```
from smb.SMBConnection import SMBConnection
c = SMBConnection("usre", "pass", "sf8008", "PC_NAME")
c.connect("1.2.3.4")
```

if it's connected it will write `True`

then you can try list shares by
```
for s in c.listShares():
  print(s.name)
```

For me this one works against W10 with disabled SMBv1
```
>>> for s in c.listShares():
...   print(s.name)
... 
ADMIN$
C$
D$
IPC$
Multimedia
```

**Comment by WanWizard** [comment]
PySMB is probably a bit ott for only share discovery.

**Comment by petrkr** [comment]
> PySMB is probably a bit ott for only share discovery.

for NetworkBrowser I need only share discovery. Somehow I need also do discovery of computers in network. For that I still can use that C library or will try do some other way.

For mounting we using CIFS kernel module which is different story.

**Comment by WanWizard** [comment]
This issue I have with it is that it's almost 1MB in size, and by using it, it has to go into every image as a dependency, also for boxes where space is a premium. And that for the 1% of functionality that is needed.

**Comment by petrkr** [comment]
> This issue I have with it is that it's almost 1MB in size, and by using it, it has to go into every image as a dependency, also for boxes where space is a premium. And that for the 1% of functionality that is needed.

pysmb is smaller than smbclient

```
-rw-r--r--    1 root     root       71.3K Aug 23 12:18 17da8dffb56894e684694e4e184ecfd3_python-pysmb_1.2.1-r0_cortexa15hf-neon-vfpv4.ipk
-rw-r--r--    1 root     root      280.7K Aug  9 03:01 2c8e19cc0152b3a526269b4123f0856c_smbclient_3.6.25-r0_cortexa15hf-neon-vfpv4.ipk
```

**Comment by WanWizard** [comment]
smbclient isn't part of an OpenPLi image either.

**Comment by persianpros** [comment]
@petrkr 

Please use image.sh now and check with samba 4.x as I removed samba 3.x

**Comment by petrkr** [comment]
> @petrkr
> 
> Please use image.sh now and check with samba 4.x as I removed samba 3.x
> 
> (smbclient_4.10.17-r0_architecture.ipk)

Installed lot of dependencies (including libpython3)

```
root@sf4008:~# smbclient -m SMB3 -g -U user -L 10.200.0.130
Enter WORKGROUP\user's password: 
dos charset 'CP850' unavailable - using ASCII
Disk|ADMIN$|Remote Admin
Disk|C$|Default share
Disk|D$|Default share
IPC|IPC$|Remote IPC
Disk|Multimedia|
Reconnecting with SMB1 for workgroup listing.
do_connect: Connection to 10.200.0.130 failed (Error NT_STATUS_RESOURCE_NAME_NOT_FOUND)
Unable to connect with SMB1 -- no workgroup available
root@sf4008:~# smbclient -V
Version 4.10.17
```

but with same kernel it works (compared to 3.x version)

**Comment by persianpros** [comment]
SMB1 is not available in OV, see: https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/recipes-connectivity/samba/samba/smb-secure.conf

**Comment by kueken** [comment]
I can't really understand it all.

This entire Samba version update is not necessary for receivers.
Version 3 of Samba 4 offers encryption for printer jobs; this is the only added value to Version 2 that can be built just as well and securely with Samba 4 as with Samba 3.
If you look at Samba 4, then the Samba3 structure is still there.

I only have the et9x00 and had the sh4 boxes available.
Samba3 worked and works fine for both.
Client and server.
For the sake of interest I would still be interested in a simple construction with a modified kernel.
Or a building from the OE core of the OE Alliance with Samba3.
This test would also have been possible from the nextp3 branch.
But now everything has already been changed.
Because there was exactly 1 problem?
But OK.
Then we can only hope that the problem is now solved.
greetings

**Comment by WanWizard** [comment]
Neither do I.

There is a known issue with enumeration of CIFS shares for servers without NetBIOS, as WS-Discovery isn't supported in our network browser yet.

There is no problem with CIFS mounts, not from clients to the box, not from the box to CIFS "servers". 

Obviously, the fact that the linux CIFS kernel driver doesn't do autodetection of the security level and the SMB version means you need to specify this in the mount options, our use the automount system in Enigma, which in OpenPLi supports autodetection of these variables. Also, the network share needs to be specified without the leading slash, recent OpenPLi's will strip it.

**Comment by petrkr** [comment]
> I can't really understand it all.
> 
> This entire Samba version update is not necessary for receivers.
> Version 3 of Samba 4 offers encryption for printer jobs; this is the only added value to Version 2 that can be built just as well and securely with Samba 4 as with Samba 3.
> If you look at Samba 4, then the Samba3 structure is still there.
> 
> I only have the et9x00 and had the sh4 boxes available.
> Samba3 worked and works fine for both.
> Client and server.
> For the sake of interest I would still be interested in a simple construction with a modified kernel.
> Or a building from the OE core of the OE Alliance with Samba3.
> This test would also have been possible from the nextp3 branch.
> But now everything has already been changed.
> Because there was exactly 1 problem?
> But OK.
> Then we can only hope that the problem is now solved.
> greetings

Communication on SMBv2 is solved by that Samba 4.10, At build Samba 3 it does not work. Maybe it needs to be enabled by some ./configure option. But It does NOT work at all with Windows box. With Another samba (server/client) of course it will work because it's compatible... Actually you DO NOT need samba (even smbclient) to mount samba shares, those two things are independent. Samba is only for server and Domain related things.. And `smbclient` was only used in new version of NetworkBrowser to discover remote shares.

I actually already tried use `pysmb` instead smbclient which works too... So yes maybe smbclient will not be used at all after refactor.

But still it is good to use up to date software than 5 years unmaintaned code into which you have to backport CVEs. Still you can disable printing stuff by --disable-cups or something like that. Soon or later will be problem compile that old samba with new glibc etc..

but again, for mounting CIFS you do not NEED samba packages at all and also samba is NOT related to kernel modules, it uses implementation in User-space.

**Comment by kueken** [comment]
From my point of view, this is all argued in a completely confused way.
Doesn't make sense.
I will never have problems compiling Samba 3. The glibc doesn't play a role at all.
There is exactly one receiver that uses the latest Linux and is currently updating it.
A kernel update can never be expected from the Hisi receivers.
Everything else is also at a standstill at the moment.
From the Image Bauer perspective, the only 5 kernel is not needed and is of little importance to users.
The Linux kernel of the receiver is there when something needs to be patched.
There is a lot going on that I learned from 2.6.32.
The kernel can also be built with the latest glibc and gcc. That the image does not start then is unfortunately due to the bootloader in front of it.
No matter
For Samba 4 remains completely nonsensical ballast for receivers.
It is also an enormous waste of resources in image building.
Nobody would notice functionally whether Samba3 or 4 is in the system.
greetings

**Comment by kueken** [comment]
The construction has been changed for a while now and there is no feedback ??
Problem solved?
Then you could close that.

**Comment by ziko-ZR1** [comment]
> The construction has been changed for a while now and there is no feedback ??
> Problem solved?
> Then you could close that.

okay i will compile a new image if the problem solved i will close this issue .
thanks

**Comment by petrkr** [comment]
Had this weekend really busy, that's why no respose, nor updated NetworkBrowser. So until NetworkBrowser get's updated this will not be resolved. It solved only half of problem. @ziko-ZR1 which file is used is sf8008 ? emmc or usb? http://openvision.yacp.net/images/sf8008/ (build from last week)

**Comment by persianpros** [comment]
Compile new images with new kernel configurations.

**Comment by ziko-ZR1** [comment]
> Had this weekend really busy, that's why no respose, nor updated NetworkBrowser. So until NetworkBrowser get's updated this will not be resolved. It solved only half of problem. @ziko-ZR1 which file is used is sf8008 ? emmc or usb? http://openvision.yacp.net/images/sf8008/ (build from last week)

thanks but i'm building the image right now

**Comment by ziko-ZR1** [comment]
apologize for the delay , the issue is still exists

![screenshot_20200830194018](https://user-images.githubusercontent.com/43075184/91666951-18ad7a80-eaf9-11ea-892e-89243af305eb.jpg)

![screenshot_20200830194025](https://user-images.githubusercontent.com/43075184/91666955-1c410180-eaf9-11ea-9065-e3c07aac04e9.jpg)

![screenshot_20200830194058](https://user-images.githubusercontent.com/43075184/91666958-1f3bf200-eaf9-11ea-94b9-31aec7424545.jpg)

![screenshot_20200830194107](https://user-images.githubusercontent.com/43075184/91666962-23680f80-eaf9-11ea-8cb6-40fc28423421.jpg)

also grab is not working with video i can only grab the osd

openatv :

![1_0_19_2074_432_1_C00000_0_0_0_20200830200218](https://user-images.githubusercontent.com/43075184/91666976-3ed31a80-eaf9-11ea-9c73-520893f01cab.jpg)

![1_0_19_2074_432_1_C00000_0_0_0_20200830200211](https://user-images.githubusercontent.com/43075184/91666980-42ff3800-eaf9-11ea-9d44-252d0d9dbc81.jpg)

**Comment by petrkr** [comment]
and issue is you have to specify "vers=2.0" but you do not want to do that? Or what is problem with mouting...

Part about mounting we tried already from command line at comment https://github.com/OpenVisionE2/openvision-development-platform/issues/34#issuecomment-679109266 where you show it works for you.

NetworkBrowser is new issue which you mention at comment https://github.com/OpenVisionE2/openvision-development-platform/issues/34#issuecomment-678776659

update samba and/or update C library netscan would solve this issue, but only if OpenVision's networks browser will be used. (Or written new one -- for which I did not get time to look at it yet)

**Comment by ziko-ZR1** [comment]
> and issue is you have to specify "vers=2.0" but you do not want to do that? Or what is problem with mouting...
> 
> Part about mounting we tried already from command line at comment [#34 (comment)](https://github.com/OpenVisionE2/openvision-development-platform/issues/34#issuecomment-679109266) where you show it works for you.
> 
> NetworkBrowser is new issue which you mention at comment [#34 (comment)](https://github.com/OpenVisionE2/openvision-development-platform/issues/34#issuecomment-678776659)
> 
> update samba and/or update C library netscan would solve this issue, but only if OpenVision's networks browser will be used. (Or written new one -- for which I did not get time to look at it yet)

i tried with and without vers=2.0 same result
