### ISSUE TITLE
**ERROR: forever-logo-cfe

### ISSUE THREAD

**Issue by alkap007** [OpenVisionE2/openvision-development-platform#36]
NOTE: Executing Tasks
**ERROR: forever-logo-cfe-1.0-r0 do_deploy: Execution of '/home/alkap/openvision-development-platform/build/tmp/work/sh4-oe-linux/forever-logo-cfe/1.0-r0/temp/run.do_deploy.38138' failed with exit code 1:
install: target '/home/alkap/openvision-development-platform/build/tmp/deploy/images/forever_9898hd/' is not a directory: No such file or directory
WARNING: /home/alkap/openvision-development-platform/build/tmp/work/sh4-oe-linux/forever-logo-cfe/1.0-r0/temp/run.do_deploy.38138:1 exit 1 from 'install -m 0644 bootloader.gz /home/alkap/openvision-development-platform/build/tmp/deploy/images/forever_9898hd/'

ERROR: Logfile of failure stored in: /home/alkap/openvision-development-platform/build/tmp/work/sh4-oe-linux/forever-logo-cfe/1.0-r0/temp/log.do_deploy.38138
Log data follows:**
| DEBUG: Executing python function sstate_task_prefunc
| DEBUG: Python function sstate_task_prefunc finished
| DEBUG: Executing shell function do_deploy
| install: target '/home/alkap/openvision-development-platform/build/tmp/deploy/images/forever_9898hd/' is not a directory: No such file or directory
| WARNING: /home/alkap/openvision-development-platform/build/tmp/work/sh4-oe-linux/forever-logo-cfe/1.0-r0/temp/run.do_deploy.38138:1 exit 1 from 'install -m 0644 bootloader.gz /home/alkap/openvision-development-platform/build/tmp/deploy/images/forever_9898hd/'
| ERROR: Execution of '/home/alkap/openvision-development-platform/build/tmp/work/sh4-oe-linux/forever-logo-cfe/1.0-r0/temp/run.do_deploy.38138' failed with exit code 1:
| install: target '/home/alkap/openvision-development-platform/build/tmp/deploy/images/forever_9898hd/' is not a directory: No such file or directory
| WARNING: /home/alkap/openvision-development-platform/build/tmp/work/sh4-oe-linux/forever-logo-cfe/1.0-r0/temp/run.do_deploy.38138:1 exit 1 from 'install -m 0644 bootloader.gz /home/alkap/openvision-development-platform/build/tmp/deploy/images/forever_9898hd/'
| 
**ERROR: Task (/home/alkap/openvision-development-platform/meta-sh4/recipes-bsp/cfe/forever-logo-cfe.bb:do_deploy) failed with exit code '1'**
NOTE: Tasks Summary: Attempted 6020 tasks of which 5992 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/alkap/openvision-development-platform/meta-sh4/recipes-bsp/cfe/forever-logo-cfe.bb:do_deploy
Summary: There were 3 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/forever_9898hd folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r208-forever_9898hd.zip

**Comment by persianpros** [comment]
Please follow the issue template, there's a reason we put it there so we could understand the problems and read things faster.
