### ISSUE TITLE
dm520 build error

### ISSUE THREAD

**Issue by zozman21** [OpenVisionE2/openvision-development-platform#36]
السلام عليكم

![5](https://user-images.githubusercontent.com/14161956/73031342-1f299480-3e3c-11ea-84e4-f4ad12200e8a.png)

**Comment by persianpros** [comment]
If you're using Ubuntu on VM, don't!

If you're using any other version but normal Ubuntu desktop, don't!

**Comment by zozman21** [comment]
i use vps linux....Previously it was working..

What happened ... Is it the new updates...
