### ISSUE TITLE
Edision OSmini not starting up Enigma2 and hangs on boot screen

### ISSUE THREAD

**Issue by WXbet** [OpenVisionE2/openvision-development-platform#37]
**Open Vision revision**
OV 10.1-r205 (Error occured no matter which revision)
BB_VERSION           = "1.47.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "osmini"
DISTRO               = "openvision"
DISTRO_VERSION       = "develop"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
VISIONVERSION        = "10.1"
VISIONREVISION       = "r205"
VISIONLANGUAGE       = "multilanguage"
BOX_BRAND            = "edision"
STB_PLATFORM         = "edisionmips"
SOC_FAMILY           = "bcm7362"
KERNELVERSION        = "4.11"
HAVE_MULTILIB        = "False"
HAVE_MIDDLEFLASH     = "True"
HAVE_SMALLFLASH      = "False"
DISPLAY_TYPE         = " 7segment     
**STB name**
osmini

**smallflash/middleflash**
middleflash

**Enigma2**
?

**Logs**
enigma2.sh > ~/debug.log 2>&1
[debug.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5075274/debug.log)

**Describe the bug**
OV hangs on boot screen. Seems that Enigma2 not starting. ssh access works.

**To Reproduce**
Flash it on osmini.

**Expected behavior**
Should start normally like on other boxes. 

**Additional context**
I can provide additional debugging information when somebody can help me with the commands.

**Comment by persianpros** [comment]
Please compile r209 and give us detailed logs: https://forum.openvision.tech/viewtopic.php?f=15&t=446

**Comment by WXbet** [comment]
The older revisions (tried it since r171) didn't boot either, I still haven't got OV 10.1 to boot on the osmini.
r209 is still compiling... Here are the logs from r209:
- [enigma2_debug.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5075389/enigma2_debug.log)
- [dmesg.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5075405/dmesg.log)
- cat /proc/stb/info/openvision
`https://openvision.tech`
- /tmp/twisted.log is not generated

**Comment by persianpros** [comment]
I think I just found the problem, it's inside enigma2

**Comment by WXbet** [comment]
Are you able to fix it?

**Comment by persianpros** [comment]
Compile now after https://github.com/OpenVisionE2/enigma2-openvision/commit/e88f698fd0fc0375b196b9b2435c652e7d057649 I think your box will be ok.

**Comment by persianpros** [comment]
The thing is we support more than 300 models and it's hard to track them all when we don't have them.

**Comment by WXbet** [comment]
Is it necessary to do some cleanups(Fast, Full, TMP, Build) before rebuild?

**Comment by persianpros** [comment]
No just run image.sh and you'll be fine.

cleanup.sh is only needed after OE upgrades (red versions).

**Comment by WXbet** [comment]
Where can I see these "red versions"?

**Comment by persianpros** [comment]
News bar in our forum, when a version is in red it means you need to use cleanup.sh (Build).

Sometimes builds get corrupted and you can use cleanup.sh (Fast).

**Comment by WXbet** [comment]
Good job @persianpros 🥇, my OSmini boots with OV 10.1 for the first time!  👍 

Building feed: There are 2 build errors with:
- [kernel-module-extrawlan-rt3070](https://github.com/OpenVisionE2/openvision-development-platform/files/5075858/log.do_compile.10020.log)
- [kernel-module-extrawlan-rtl8192cu](https://github.com/OpenVisionE2/openvision-development-platform/files/5075994/log.do_compile.15249.log)

Maybe you can take a look at this. I removed these 2 modules from openvision-enigma2-feed.bb, now the feed for osmini is building successfully.

**Comment by persianpros** [comment]
Glad to hear it's ok now :)

Regarding extra kernel modules we need to use more of our "KERNELVERSION" variable and fix those.

**Comment by persianpros** [comment]
@WXbet 

I forgot to ask how is the performance of OV on osmini?

**Comment by WXbet** [comment]
Performance ist okay. Menus run very smoothly.
