### ISSUE TITLE
i still can't build the image for vusolo

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/openvision-development-platform#37]
ERROR: linux-vuplus-3.9.6-openvision do_compile: oe_runmake failed
ERROR: linux-vuplus-3.9.6-openvision do_compile: Execution of '/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.6148' failed with exit code 1:
  GEN     /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
scripts/kconfig/conf --silentoldconfig Kconfig
  GEN     /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
  WRAP    arch/mips/include/generated/asm/trace_clock.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  Using /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source as source for kernel
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/sortextable
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/devicetable-offsets.s
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:64:1: warning: 'succeed_file' defined but not used [-Wunused-function]
   64 | succeed_file(void)
      | ^~~~~~~~~~~~
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/mod/sumversion.o
In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:162:
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c: In function 'main':
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
  158 |   memset(relocs, 0, relocs_size);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  104 |  int relocs_size;
      |      ^~~~~~~~~~~
In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler.h:54,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/stddef.h:1,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/stddef.h:4,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/posix_types.h:4,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/types.h:13,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/types.h:5,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/mod_devicetable.h:11,
                 from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/devicetable-offsets.c:2:
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler-gcc.h:103:1: fatal error: linux/compiler-gcc9.h: No such file or directory
  103 | #include gcc_header(__GNUC__)
      | ^~~~
compilation terminated.
make[4]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/Makefile:35: scripts/mod/devicetable-offsets.s] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:160:
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
  158 |   memset(relocs, 0, relocs_size);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  104 |  int relocs_size;
      |      ^~~~~~~~~~~
make[3]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/Makefile.build:454: scripts/mod] Error 2
make[2]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/Makefile:518: scripts] Error 2
make[1]: *** [Makefile:130: sub-make] Error 2
make: *** [Makefile:26: all] Error 2
WARNING: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.6148:1 exit 1 from 'exit 1'

ERROR: Logfile of failure stored in: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/log.do_compile.6148
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 10 HOSTCC=gcc  -isystem/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/include -O2 -pipe -L/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/lib                         -L/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/lib                         -Wl,-rpath,/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native/lib                         -Wl,-O1 HOSTCPP=gcc  -E vmlinux CC=mipsel-oe-linux-gcc  -fuse-ld=bfd -fdebug-prefix-map=/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision=/usr/src/debug/linux-vuplus/3.9.6-openvision                      -fdebug-prefix-map=/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot=                      -fdebug-prefix-map=/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/recipe-sysroot-native=  -fdebug-prefix-map=/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source=/usr/src/kernel   LD=mipsel-oe-linux-ld.bfd
|   GEN     /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
| scripts/kconfig/conf --silentoldconfig Kconfig
|   GEN     /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
|   WRAP    arch/mips/include/generated/asm/trace_clock.h
|   CHK     include/generated/uapi/linux/version.h
|   UPD     include/generated/uapi/linux/version.h
|   CHK     include/generated/utsrelease.h
|   UPD     include/generated/utsrelease.h
|   Using /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source as source for kernel
|   HOSTCC  scripts/kallsyms
|   HOSTCC  scripts/conmakehash
|   HOSTCC  scripts/sortextable
|   CC      scripts/mod/empty.o
|   HOSTCC  scripts/mod/mk_elfconfig
|   CC      scripts/mod/devicetable-offsets.s
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:64:1: warning: 'succeed_file' defined but not used [-Wunused-function]
|    64 | succeed_file(void)
|       | ^~~~~~~~~~~~
|   MKELF   scripts/mod/elfconfig.h
|   HOSTCC  scripts/mod/modpost.o
|   HOSTCC  scripts/mod/sumversion.o
| In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:162:
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c: In function 'main':
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
|   158 |   memset(relocs, 0, relocs_size);
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
|   104 |  int relocs_size;
|       |      ^~~~~~~~~~~
| In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler.h:54,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/stddef.h:1,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/stddef.h:4,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/posix_types.h:4,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/types.h:13,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/types.h:5,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/mod_devicetable.h:11,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/devicetable-offsets.c:2:
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler-gcc.h:103:1: fatal error: linux/compiler-gcc9.h: No such file or directory
|   103 | #include gcc_header(__GNUC__)
|       | ^~~~
| compilation terminated.
| make[4]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/Makefile:35: scripts/mod/devicetable-offsets.s] Error 1
| make[4]: *** Waiting for unfinished jobs....
| In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:160:
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
|   158 |   memset(relocs, 0, relocs_size);
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
|   104 |  int relocs_size;
|       |      ^~~~~~~~~~~
| make[3]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/Makefile.build:454: scripts/mod] Error 2
| make[2]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/Makefile:518: scripts] Error 2
| ERROR: oe_runmake failed
| make[1]: *** [Makefile:130: sub-make] Error 2
| make: *** [Makefile:26: all] Error 2
| WARNING: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.6148:1 exit 1 from 'exit 1'
| ERROR: Execution of '/home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.6148' failed with exit code 1:
|   GEN     /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
| scripts/kconfig/conf --silentoldconfig Kconfig
|   GEN     /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/build/Makefile
|   WRAP    arch/mips/include/generated/asm/trace_clock.h
|   CHK     include/generated/uapi/linux/version.h
|   UPD     include/generated/uapi/linux/version.h
|   CHK     include/generated/utsrelease.h
|   UPD     include/generated/utsrelease.h
|   Using /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source as source for kernel
|   HOSTCC  scripts/kallsyms
|   HOSTCC  scripts/conmakehash
|   HOSTCC  scripts/sortextable
|   CC      scripts/mod/empty.o
|   HOSTCC  scripts/mod/mk_elfconfig
|   CC      scripts/mod/devicetable-offsets.s
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:64:1: warning: 'succeed_file' defined but not used [-Wunused-function]
|    64 | succeed_file(void)
|       | ^~~~~~~~~~~~
|   MKELF   scripts/mod/elfconfig.h
|   HOSTCC  scripts/mod/modpost.o
|   HOSTCC  scripts/mod/sumversion.o
| In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:162:
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c: In function 'main':
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
|   158 |   memset(relocs, 0, relocs_size);
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
|   104 |  int relocs_size;
|       |      ^~~~~~~~~~~
| In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler.h:54,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/stddef.h:1,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/stddef.h:4,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/posix_types.h:4,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/uapi/linux/types.h:13,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/types.h:5,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/mod_devicetable.h:11,
|                  from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/devicetable-offsets.c:2:
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/include/linux/compiler-gcc.h:103:1: fatal error: linux/compiler-gcc9.h: No such file or directory
|   103 | #include gcc_header(__GNUC__)
|       | ^~~~
| compilation terminated.
| make[4]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/mod/Makefile:35: scripts/mod/devicetable-offsets.s] Error 1
| make[4]: *** Waiting for unfinished jobs....
| In file included from /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.c:160:
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
|   158 |   memset(relocs, 0, relocs_size);
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
|   104 |  int relocs_size;
|       |      ^~~~~~~~~~~
| make[3]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/scripts/Makefile.build:454: scripts/mod] Error 2
| make[2]: *** [/home/zakaria/openvision/openvision-development-platform/build/tmp/work-shared/vusolo/kernel-source/Makefile:518: scripts] Error 2
| make[1]: *** [Makefile:130: sub-make] Error 2
| make: *** [Makefile:26: all] Error 2
| WARNING: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/vusolo-oe-linux/linux-vuplus/3.9.6-openvision/temp/run.do_compile.6148:1 exit 1 from 'exit 1'
| 
ERROR: Task (/home/zakaria/openvision/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus_3.9.6.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3151 tasks of which 352 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/zakaria/openvision/openvision-development-platform/meta-vuplus/recipes-bsp/linux/linux-vuplus_3.9.6.bb:do_compile
Summary: There were 22 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:96: image] Error 1

**Comment by persianpros** [comment]
Please update your Open Vision and try again.
