### ISSUE TITLE
ERROR..fp-control_git.bb:do_install) failed with exit code '1'

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#39]
`ERROR: fp-control-gitAUTOINC+3d65396e74-r0 do_install: Execution of '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/temp/run.do_install.3044245' failed with exit code 1:
make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build'
make[1]: Nothing to be done for 'install-data-am'.
 /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin'
  ./sh4-oe-linux-libtool   --mode=install /home/atef/openvision-development-platform/build/tmp/hosttools/install -c fp_control '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin'
sh4-oe-linux-libtool: install: /home/atef/openvision-development-platform/build/tmp/hosttools/install -c fp_control /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin/fp_control
make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build'
install: cannot stat '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build/fp-control': No such file or directory
WARNING: /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/temp/run.do_install.3044245:1 exit 1 from 'install -m 0755 /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build/fp-control /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/bin/'

ERROR: Logfile of failure stored in: /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/temp/log.do_install.3044245
Log data follows:
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'sh-common', 'common-linux', 'common-glibc', 'sh4-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/autoconf/autoconf_2.69.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/libtool/libtool-cross_2.4.6.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/libtool/libtool-native_2.4.6.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/meta-openvision/recipes-devtools/gcc4/gcc-cross_4.9.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/meta-sh4/recipes-bsp/drivers/sh4-dvb-modules.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/gnu-config/gnu-config_git.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc_2.25.bb:do_populate_sysroot', 'virtual:native:/home/atef/openvision-development-platform/openembedded-core/meta/recipes-devtools/automake/automake_1.16.2.bb:do_populate_sysroot', '/home/atef/openvision-development-platform/meta-openvision/recipes-devtools/gcc4/gcc-runtime_4.9.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['autoconf-native', 'libtool-cross', 'libtool-native', 'gcc-cross-sh4', 'quilt-native', 'patch-native', 'pseudo-native', 'sh4-dvb-modules', 'gnu-config-native', 'glibc', 'automake-native', 'gcc-runtime', 'texinfo-dummy-native', 'm4-native', 'libmpc-native', 'mpfr-native', 'binutils-cross-sh4', 'gmp-native', 'zlib-native', 'linux-libc-headers', 'stlinux24-sh4-stx7111-fdma-firmware', 'attr-native', 'libgcc', 'xz-native', 'flex-native', 'gettext-minimal-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| NOTE: make -j 8 DRIVER_TOPDIR=/home/atef/openvision-development-platform/build/tmp/work-shared/spark/kernel-source DESTDIR=/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image install
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build'
| make[1]: Nothing to be done for 'install-data-am'.
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin'
|   ./sh4-oe-linux-libtool   --mode=install /home/atef/openvision-development-platform/build/tmp/hosttools/install -c fp_control '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin'
| sh4-oe-linux-libtool: install: /home/atef/openvision-development-platform/build/tmp/hosttools/install -c fp_control /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin/fp_control
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build'
| install: cannot stat '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build/fp-control': No such file or directory
| WARNING: /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/temp/run.do_install.3044245:1 exit 1 from 'install -m 0755 /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build/fp-control /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/bin/'
| ERROR: Execution of '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/temp/run.do_install.3044245' failed with exit code 1:
| make[1]: Entering directory '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build'
| make[1]: Nothing to be done for 'install-data-am'.
|  /home/atef/openvision-development-platform/build/tmp/hosttools/mkdir -p '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin'
|   ./sh4-oe-linux-libtool   --mode=install /home/atef/openvision-development-platform/build/tmp/hosttools/install -c fp_control '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin'
| sh4-oe-linux-libtool: install: /home/atef/openvision-development-platform/build/tmp/hosttools/install -c fp_control /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/usr/bin/fp_control
| make[1]: Leaving directory '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build'
| install: cannot stat '/home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build/fp-control': No such file or directory
| WARNING: /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/temp/run.do_install.3044245:1 exit 1 from 'install -m 0755 /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/build/fp-control /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/fp-control/gitAUTOINC+3d65396e74-r0/image/bin/'
| 
ERROR: Task (/home/atef/openvision-development-platform/meta-sh4/recipes-bsp/sh4-apps/fp-control_git.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7079 tasks of which 3 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-sh4/recipes-bsp/sh4-apps/fp-control_git.bb:do_install
Summary: There were 4 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/spark folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r209-spark.zip
atef@ganm:~/openvision-development-platform$ 
`

**Comment by persianpros** [comment]
I know what's wrong, soon will be fixed.

**Comment by persianpros** [comment]
Should be fixed now.
