### ISSUE TITLE
ERROR: ParseError at sh4-apps/sh4-bin-install.inc1: unparsed line: 'SH4APPBIN ?= ${PN}'

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#40]
`Building image for spark
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |                                                                                                                                                                              | ETA:  --:--:--
Loaded 0 entries from dependency cache.
ERROR: ParseError at /home/atef/openvision-development-platform/meta-sh4/recipes-bsp/sh4-apps/sh4-bin-install.inc:1: unparsed line: 'SH4APPBIN ?= ${PN}'                                            | ETA:  0:02:25

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Error 1
atef@ganm:~/openvision-development-platform$`

**Comment by persianpros** [comment]
Hains fixed this yesterday, your OE isn't up-to-date so use update.sh
