### ISSUE TITLE
dags and compiler-gcc9.h: No such file or directory

### ISSUE THREAD

**Issue by TodorGeshev** [OpenVisionE2/openvision-development-platform#42]
Im trying build for optimussos2plus machine
/src/openvisision/openvision-development-platform/build/tmp/work-shared/optimussos2plus/kernel-source/include/linux/compiler-gcc.h:103:1: fatal error: linux/compiler-gcc9.h: No such file or directory

What to do ?

**Comment by persianpros** [comment]
Give me some time please, I will fix this tomorrow.

**Comment by persianpros** [comment]
Ok please update your Open Vision and try again.
