### ISSUE TITLE
Understanding Software Update Message 

### ISSUE THREAD

**Issue by WXbet** [OpenVisionE2/openvision-development-platform#44]
I've setup a local private update feed. One question and one hint regarding executing software update check via enigma2:
**Q: Why is this message displayed?**
![Message](https://user-images.githubusercontent.com/57314510/91042393-f5bf2a00-e611-11ea-9213-d3ef1d2248a1.JPG)
**H: There is missing a whitespace between the german word `da` and `openvision.tech`**
![Message](https://user-images.githubusercontent.com/57314510/91042393-f5bf2a00-e611-11ea-9213-d3ef1d2248a1.JPG)

**Comment by persianpros** [comment]
Seems like a translation problem so maybe it's in https://github.com/OpenVisionE2/enigma2-openvision/tree/develop/po

**Comment by WXbet** [comment]
I'll take a look.

**Comment by WXbet** [comment]
Yes.
Line 12736
WRONG: msgstr "Der Status des aktuellen Images konnte nicht überprüft werden, da% s nicht erreicht werden kann."
CORRECT: msgstr "Der Status des aktuellen Images konnte nicht überprüft werden, da %s nicht erreicht werden kann."

There are many "% s" strings in this file. All of this were typos I think.

**Comment by WXbet** [comment]
And why is this message displayed?
