### ISSUE TITLE
OpenWebIf remote not working

### ISSUE THREAD

**Issue by WXbet** [OpenVisionE2/openvision-development-platform#46]
OpenVision 10.2 r220 and higher.

Using the remote in OpenWebif has no effect. E.g. clicking Menu- or OK-button don't show any menu in screenshot.
Tested on dm900, dm525, osmini, vusolo2, vusolose, vuzero4k.

**Comment by persianpros** [comment]
Please follow the issue template.

P.S. I'm checking the Open WebIF so no need for this again :+1:
