### ISSUE TITLE
dm900 enigma2 startup loop after flashing

### ISSUE THREAD

**Issue by WXbet** [OpenVisionE2/openvision-development-platform#47]
OV 10.2 r221

After flashing via Revocery console or ofgwrite enigma not starting up. The progess bar in the OLED display indicates a start loop.

Flashing an 10.1 image (e.g. r216) an the online upgrading via feed works without problems.

**Comment by persianpros** [comment]
Hello,

Please use our issue template and attach logs otherwise there's nothing we can do for just a "not working" message.

**Comment by WXbet** [comment]
I provide a log later

**Comment by WXbet** [comment]
Hi @persianpros:

Can you please reopen the Ticket. See the logs attached:
- [enigma2.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5123556/enigma2.log)
- [dmesg.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5123557/dmesg.log)
- [openvision.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5123570/openvision.log)
- [twisted.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5123572/twisted.log)

**Comment by persianpros** [comment]
Install python-pysmb and let me know if it fixes the problem.

**Comment by WXbet** [comment]
Installing python-pysmb brings no effect. Still looping. I build a new image...

**Comment by WXbet** [comment]
New image 10.2-r222, STILL LOOPING.

**Comment by persianpros** [comment]
Please attach new logs (enigma2 is enough for now).

**Comment by WXbet** [comment]
- [enigma2.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5124398/enigma2.log)

Reinstalling python-pysmb, curl, nfs-utils, enigma2-plugin-extensions-openwebif-themes and enigma2-plugin-systemplugins-osd3dsetup that was remove in https://github.com/OpenVisionE2/openvision-development-platform/commit/36051d753a71f54a08178776ddc0ed22eaa6a534 don't fix it.

**Comment by WXbet** [comment]
This is a working one from a restored image:
[enigma22.log](https://github.com/OpenVisionE2/openvision-development-platform/files/5124522/enigma22.log)

Maybe it helps for comparision.

**Comment by persianpros** [comment]
netifaces.so: file too short

tells your build is corrupted so did you try after cleanup.sh (Build)?

**Comment by WXbet** [comment]
You are right 🥇 
python-netifaces_0.10.9-r0_cortexa15hf-neon-vfpv4.ipk contains a 0-byte netifaces.so 👎

**Comment by WXbet** [comment]
cleanup.sh FULL and then image.sh did not resolve this problem.

To resolve it, I had to run:
```
cd build
source env.source
MACHINE=dm900 bitbake python-netifaces -c do_cleanall
MACHINE=dm900 bitbake python-netifaces -c do_build
./image.sh
```
netifaces.so > 0 byte 👍 

After flashing the loop is away. Thank you very much @persianpros. 👍

**Comment by persianpros** [comment]
Your build is corrupted and you'll get more errors later, you need to use cleanup.sh Build not Full.
