### ISSUE TITLE
Open Vision 10.2 sh4 : remote control not responding

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-development-platform#48]
**Open Vision revision**
it's OV 10.2-226

**STB name**
Spark 7111
**smallflash/middleflash**
smallflash
**Enigma2**
26-8-2020
**Logs**
cannot take
**Describe the bug**
after installing enigma2 remote control not responding

**Comment by persianpros** [comment]
We know and we're talking about it: https://forum.openvision.tech/viewtopic.php?f=12&t=811 (Private test section)

Also there's no such thing as "cannot take" for logs as taking a log isn't related to a remote.
