### ISSUE TITLE
Build feed

### ISSUE THREAD

**Issue by TodorGeshev** [OpenVisionE2/openvision-development-platform#48]
Now Vision is ok for optimussos2plus thanks
But building feeds run forever on nodejs do_compile.
And I still have to remove 7603u from the enigma feed

**Comment by persianpros** [comment]
I didn't check feed for all the boxes yet because I have no time for it, how is Open Vision on your STB? Can you share a screenshot of About screen?

**Comment by TodorGeshev** [comment]
I just build the image, box is still with 7.3

**Comment by persianpros** [comment]
Use "image.sh" again and let me know if the feed is ok.

**Comment by TodorGeshev** [comment]
Vision and Feed builds fine ! Without handwork , thanks 
Will test image this wekeend
