### ISSUE TITLE
Build size over the box size

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/openvision-development-platform#49]
i built the image for vusolo but the image size is over 100mb i even tried to remove plugins that i don't need but still get the same size 

![Screenshot from 2020-02-11 15-37-54](https://user-images.githubusercontent.com/43075184/74258377-811c4200-4cf6-11ea-8564-47473593ad90.png)

**Comment by persianpros** [comment]
Thanks for the report :+1: 

I missed this and now fixed, please run image.sh again and compile a new image.
