### ISSUE TITLE
We only support Ubuntu 20.04.x LTS!

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#49]
**Why the build does not support the operating system
I have 20.10**

`atef@ganm:~/openvision-development-platform$ ./image.sh

-e 

-e We only support Ubuntu 20.04.x LTS!

-e 

atef@ganm:~/openvision-development-platform$ 
`
![Screenshot_٢٠٢٠٠٨٢٨_٠٨٢٠٣٥](https://user-images.githubusercontent.com/31848885/91529009-cc034d00-e908-11ea-9d24-09365cf1bdff.png)

**Comment by persianpros** [comment]
Answered in the forum.
