### ISSUE TITLE
Octagon sf8008 grab should be in sf8008 repository

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#50]
**Open Vision revision**
Tell us it's OV 10.2-r231

This package should be in sf8008 ipk repository, now it's in `cortexa15hf-neon-vfpv4` so also octagon sf4008 installs it as webif dependency. It leads to screenshot on web interface does not works, because missing library.
```
root@sf4008:~# /usr/bin/grab 
/usr/bin/grab: error while loading shared libraries: libhi_common.so: cannot open shared object file: No such file or directory
```

after manual uninstall and replace by aio-grab it works on sf4008

if I will know where change repository, I will do PR, but since I do not found that, this way could be faster for you
```
root@sf4008:~# opkg info octagon-grab-hisi3798mv200
Package: octagon-grab-hisi3798mv200
Version: 20180301-r0
Depends: libc6 (>= 2.32), libstdc++6 (>= 10.2.0)
Provides: aio-grab
Replaces: aio-grab
Conflicts: aio-grab
Status: install ok installed
Section: base
Architecture: cortexa15hf-neon-vfpv4
Maintainer: OE-Core Developers <openembedded-core@lists.openembedded.org>
MD5Sum: 4202931b648a1d63a5d50c6603e9bb1d
Size: 11534
Filename: octagon-grab-hisi3798mv200_20180301-r0_cortexa15hf-neon-vfpv4.ipk
Source: octagon-grab-hisi3798mv200.bb
Description: grab for sf8008
Installed-Size: 35284
Installed-Time: 1598285576
```

https://github.com/OpenVisionE2/meta-octagon/blob/0c8a1d4a97205d429b0fdba6f585ca2d8229204f/recipes-bsp/grab/octagon-grab-hisi3798mv200.bb

**Comment by persianpros** [comment]
Thanks for the report, fix pushed :+1:
