### ISSUE TITLE
Some build errors with transaltions

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#53]
Also figured out some problems with transaltion `po` files. First problem was at enhanced movie center, so I again did clean build and seems it's not alone package, now it got also on yahoo weather. Maybe some changed syntax, so now it says errors.. Keep this thread for investigate. Also more run means new errors, seems like random.

```
msgfmt -o tr.mo tr.po
../xml2po.py ../ >> YahooWeather.pot
........ done.
........ done.
de.po:256:11: syntax error
/home/builder/openvision-development-platform/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-yahooweather/1.2.+gitAUTOINC+f04f398ad7-r0/recipe-sysroot-native/usr/bin/msgfmt: found 1 fatal error
make[2]: *** [Makefile:486: de.mo] Error 1
make[2]: *** Waiting for unfinished jobs....
........ done.
```

**Comment by petrkr** [comment]
after few next tries it works fine.. Sometimes packages have problem with concuret build (like make -jX where X > 1). Maybe it can be this problem?

**Comment by 4l3x2k** [comment]
I think sometimes concurrency can be a problem. Even in Bitbake there are such errors. For example do_deploy cannot run in parallel with do_package I think. See latest commits from openembedded. This is the effect of BB_THREADS and not MAKE_THREADS in site.conf.

**Comment by petrkr** [comment]
I did not got this problem again even clean builds. Seems it's solved meanwhile by updating bitbake or something.. Closing for now, If I will see that again I will reopen or do new.
