### ISSUE TITLE
Wlan Network

### ISSUE THREAD

**Issue by abootorab** [OpenVisionE2/openvision-development-platform#54]
There is no wlan option in the Network section
In open vision 9.3

**Comment by persianpros** [comment]
Which STB? What WLAN do you have?

**Comment by abootorab** [comment]
> Which STB? What WLAN do you have?

Hi dear friend
STB: Vu+ solo 4k
Wlan: linksys
After selecting the Network option instead of LAN and WLAN options there are other options, one of which is Device option
Thanks

**Comment by kueken** [comment]
You will need the driver for your device, which is usually built into the feed.
The driver is always the chipset.
So not manufacturer 'linksys' but look for the chipset and then install the driver.
It is not a build error because you cannot install all possible drivers directly.

greetings

**Comment by abootorab** [comment]
> You will need the driver for your device, which is usually built into the feed.
> The driver is always the chipset.
> So not manufacturer 'linksys' but look for the chipset and then install the driver.
> It is not a build error because you cannot install all possible drivers directly.
> 
> greetings

Thank you so much
But I have both LAN and WLAN options in the openatv image but not in the openvision image.  What should I do now to solve this problem?

**Comment by kueken** [comment]
Your box does not recognize the WiFi stick under the image.
The driver must first be installed, then the WLAN stick will be recognized.
Then the menu regarding WiFi should be activated.
It is no different with OpenATV.
You will probably have built the chipset directly by chance.
It is possible that the defconfig must also be adjusted.
But before all of that you need to know which chipset it is.

**Comment by abootorab** [comment]
> Your box does not recognize the WiFi stick under the image.
> The driver must first be installed, then the WLAN stick will be recognized.
> Then the menu regarding WiFi should be activated.
> It is no different with OpenATV.
> You will probably have built the chipset directly by chance.
> It is possible that the defconfig must also be adjusted.
> But before all of that you need to know which chipset it is.

Thanks for your tips
