### ISSUE TITLE
"Now playing" EPG under OK button is unaccurate in NHK world

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#54]
Sometimes happen EPG show future program on NHK world in info status bar under "OK" button, but Single Channel EPG and channel list shows right program.

![1_0_1_139D_3EA_1_C00000_0_0_0_20200919145112](https://user-images.githubusercontent.com/6428351/93667703-3468c880-fa88-11ea-9717-6f683c6963bf.jpg)
![1_0_1_139D_3EA_1_C00000_0_0_0_20200919145051](https://user-images.githubusercontent.com/6428351/93667704-3599f580-fa88-11ea-9cc4-0901db400649.jpg)
![1_0_1_139D_3EA_1_C00000_0_0_0_20200919145026](https://user-images.githubusercontent.com/6428351/93667705-3599f580-fa88-11ea-94db-3cb8dbbacace.jpg)

**Comment by norhap** [comment]
1.- when something like this happens, epg cache should be removed.

<a href='https://postimg.cc/pmbSCRrk' target='_blank'><img src='https://i.postimg.cc/nhCtHLJ8/1-0-19-7539-426-1-C00000-0-0-0-20201020175447.jpg' border='0' alt='1-0-19-7539-426-1-C00000-0-0-0-20201020175447'/></a>
2.- Now New Download EPG cache.
3.-if the problem persists and reoccurs, then the sources you take for EPG are not correct, use download alternatives in the form of plugin, CrossEPG, EPG-Import ... go testing stability.

**Comment by petrkr** [comment]
I do not use any EPG online service, all is downloaded from transponder data. I can ty that delete EPG if that will help. Let you know later.

It actually happens only sometimes.

**Comment by norhap** [comment]
So...
EPG Settings:
Enable EIT EPG and Enable MHW EPG.

**Comment by fairbird** [comment]
This is not problem ... just some times failure for import and download Epg from some transponder data.
And then the Epg date will be corrupted...
 Just delete it or full reboot device ...

**Comment by petrkr** [comment]
Ok consider bad data in EPG.
Then why in Single-channel EPG winows I can see it right. But in "OK" status bar it's broken? It seems like those data could be mixed (like in array[0] is later program and status bar order by array[0] and array[1], but single EPG order by datetime) ?

**Comment by fairbird** [comment]
As I said friend .. The issue from incorrect time and date .. See the screenshots 

The time (not correct) Because I reboot my box from channel does not have Epg program ...
.
![1](https://user-images.githubusercontent.com/1761779/96638441-c9314100-1328-11eb-9870-5fde5e7c2c36.jpg)
.
![2](https://user-images.githubusercontent.com/1761779/96638446-cb939b00-1328-11eb-9698-eb1ec01f610f.jpg)
.
After I stop on MBC channe (It have Epg program) and restart enigma2 (Every thing ok Time + Epg)
.
![3](https://user-images.githubusercontent.com/1761779/96638450-cc2c3180-1328-11eb-8963-f5c4153f4ac7.jpg)
.
![5](https://user-images.githubusercontent.com/1761779/96638453-ccc4c800-1328-11eb-930d-62a595228503.jpg)

**Comment by petrkr** [comment]
Check my screenshots, my date/time is correct in all screenshots. I understand if time is bad it will show bad data. But also it's only this channel (which I noticed) other channels does not have that issue. If you will point me where I can check source code of this status bar, I can try debug that and find out what is wrong with this channel (again, since I do not watch all 1200 channels I notice it only on this NHK @ Astra 19.2E)

**Comment by fairbird** [comment]
1-Enable Twisted log from (menu > setup > system > Gui settings > Log settings)
2- Restart enigma2 with debug

Then you will be find debug log in path of log what you choose from Log settings
And also Twisted log you find it in /tmp

open it and see If you can find any error

**Comment by petrkr** [comment]
Right now I had same problem. I deleted epg cache, reboot and now I can see only EPG for next hour.. I think they have some malformed EPG in TS stream...  And seems like "OK" button looks to aired EPG while Single channel and channel list also took cached one. That's could be why those two list are "up to date" and status bar not.

Now when I deleted EPG cache I can not see in channel list nothing (empty) and in "single channel epg" I have first event at 2am CEST (next hour from now).

But since "what i see in air program" that programs are exact in EPG, so it's not problem like UTC or Local time (what mostly happens on cheap receivers during summer/winter time)

**Comment by petrkr** [comment]
I do not know if you can catch Astra 19.2E to see at your side

**Comment by fairbird** [comment]
I have 19.2E but in Middle east (Gulf) we can only reach some frequencies ..
That frequency appears in your screen shot I can not reach it ...

**Comment by persianpros** [comment]
@petrkr 

Not related to this issue but you may want to look at https://forum.openvision.tech/viewtopic.php?f=16&t=852

**Comment by petrkr** [comment]
Here is video how that status bar EPG going to be replaced after channel switch. 

https://youtu.be/YEboukptokE

**Comment by petrkr** [comment]
Ok found workaround for this
  If I disable this option then stay that cached EPG in status bar.

It must be problem with that channel as I post before, after EPG delete there is really not aired that current event, but some next (that visible in statusbar)

![1_0_1_139D_3EA_1_C00000_0_0_0_20201025125254](https://user-images.githubusercontent.com/6428351/97106310-10b92380-16c1-11eb-9de4-e16f1df2e577.jpg)

**Comment by petrkr** [comment]
https://digitalbitrate.com/dtv.php?lang=en&live=61&mux=11229&pid=5021&nav=cha&ssnav=N

Yes aired EIT table is wrong from them.

**Comment by petrkr** [comment]
Closing... Reported to Astra 1KR provider.. Since here workaround exists and actually it's not problem of enigma2.
