### ISSUE TITLE
low prio: Setup-->Settings-->EPG has bad string format in description

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#55]
On few items there is bad string.format() on item description. See screenshot. (%s instead expand)

Keeping here just for track/remember that issue. It's low prio

![1_0_1_6FF1_436_1_C00000_0_0_0_20200922225213](https://user-images.githubusercontent.com/6428351/93936586-ac541e80-fd26-11ea-80b1-c146093273ff.jpg)

**Comment by norhap** [comment]
thx @petrkr for report.
fixed:
https://github.com/OpenVisionE2/enigma2-openvision/commit/4982bc04f6a7ac8313f006e6ce04d29976fd0c84
