### ISSUE TITLE
can't mount loopback devices!!!

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-development-platform#56]
please include loop.ko module in sh4 linux kernel as when i type
`modeprobe loop
 `
the output is like:
`modprobe: FATAL: Module loop not found in directory /lib/modules/2.6.32.71_stm24_0217
`

**Comment by persianpros** [comment]
If you mean "CONFIG_BLK_DEV_LOOP" it's built-in and not available as .ko module.

**Comment by ahmedmoselhi** [comment]
so how to use loop devices???
