### ISSUE TITLE
builde error sf8008

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#60]
lately (sorry do not know commit) there is problem with change permissions for SF8008 images:

```| 
ERROR: Task (/home/builder/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_image_octagonemmc) failed with exit code '1'
```

```
...
| cp: failed to preserve ownership for /home/builder/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/deploy-openvision-enigma2-image-image-complete/userdata/linuxrootfs1/var/log: Operation not permitted
| cp: failed to preserve ownership for /home/builder/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/deploy-openvision-enigma2-image-image-complete/userdata/linuxrootfs1/var/run: Operation not permitted
| cp: failed to preserve ownership for /home/builder/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/deploy-openvision-enigma2-image-image-complete/userdata/linuxrootfs1/var/tmp: Operation not permitted
| cp: failed to preserve ownership for '/home/builder/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/deploy-openvision-enigma2-image-image-complete/userdata/linuxrootfs1/var/volatile': Operation not permitted
...

```

**Comment by persianpros** [comment]
Try cleanup.sh (Fast) maybe there are some remaining files there.

**Comment by petrkr** [comment]
nope, clean up does not help :( Maybe I can over night try clean-build

**Comment by petrkr** [comment]
still not working, I will try clean-build now. See you in few hours :)

**Comment by norhap** [comment]
Please report if this problem persists.

**Comment by petrkr** [comment]
Must be something changed in bitbake's environmet... Because if I will run that run.do_image.... by hand from shell, that script itself work fine. So it seems like bitbucket run under some other user and try change owner ship to builder user (that only one user in that ubuntu builder).. I had similar problem when I did builds in docker before.

[Uploading log.do_image_octagonemmc.3999437.txt…]()

**Comment by norhap** [comment]
@petrkr can you do the manual change and check if it works?

**Comment by norhap** [comment]
WARNING: /pen_compile/openvision//build/tmp/work/gbtrio4k-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/temp/run.do_image_gigablueemmc.1502:154 exit 1 from '**cp -a** /pen_compile/openvision/build/tmp/work/gbtrio4k-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/rootfs/* /pen_compile/openvision//build/tmp/work/gbtrio4k-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/deploy-openvision-enigma2-image-image-complete/userdata/linuxrootfs1/'

https://github.com/OpenVisionE2/meta-octagon/commit/7c95cae6ac72ad5985899507745228a6143e428d
