### ISSUE TITLE
Builing image fails: do not use Bitbake as root

### ISSUE THREAD

**Issue by muelli75** [OpenVisionE2/openvision-development-platform#61]
Building an image with the repository of today on latest Ubuntu 18.04 fails, because

---
Makefile:98: recipe for target "image" failed
make: *** [image] Error 1
Building image for vuuno4kse
ERROR: OE-core's config sanity checker detected a potential misconfiguration.
Either fix the cause of this error or at your own risk disable the checker (see sanity.conf)
Following is the list of potential problems/advisories:

Do not use Bitbake as root.
---

Any ideas how to solve this?

Thanks for take notice of this issue.

**Comment by persianpros** [comment]
You should not use "sudo" or "su", as you could see "Do not use bitbake as root".

**Comment by muelli75** [comment]
thank you for opening my eyes ...

**Comment by persianpros** [comment]
;) I myself lose my sight sometimes don't worry.
