### ISSUE TITLE
ERROR enigma2-alliance-plugins...

### ISSUE THREAD

**Issue by aouamed** [OpenVisionE2/openvision-development-platform#63]
LAST UPDATE 
/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-alliance-plugins/gitAUTOINC+531295d715-r0/recipe-sysroot-native/usr/bin/msgmerge: found 1872 fatal errors
make[3]: *** [Makefile:494: zh_CN.po] Error 1
make[3]: Leaving directory '/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-alliance-plugins/gitAUTOINC+531295d715-r0/git/LCD4linux/po'
make[2]: *** [Makefile:377: all-recursive] Error 1
make[2]: Leaving directory '/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-alliance-plugins/gitAUTOINC+531295d715-r0/git/LCD4linux'
make[1]: *** [Makefile:424: all-recursive] Error 1
make[1]: Leaving directory '/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-alliance-plugins/gitAUTOINC+531295d715-r0/git'
make: *** [Makefile:356: all] Error 2
ERROR: oe_runmake failed
WARNING: /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-alliance-plugins/gitAUTOINC+531295d715-r0/temp/run.do_compile.3423410:189 exit 1 from 'exit 1'

**Comment by persianpros** [comment]
Thanks for the report, zh_CN.po for Blindscan (from OE-A) had problem and should be ok now.
