### ISSUE TITLE
Bug report for Open Vision 10.2 netbase_6.1 and replex-0.1.6.8 missing

### ISSUE THREAD

**Issue by MasterRoCcO** [OpenVisionE2/openvision-development-platform#64]
**Open Vision revision**
Tell us it's OV 10.2-r244?

**STB vuultimo4k**
WARNING: replex-0.1.6.8-r0 do_fetch: Failed to fetch URL http://repository.slacky.eu/slackware-12.2/multimedia/replex/0.1.6.8/src/replex-0.1.6.8.tar.gz, attempting MIRRORS if available
WARNING: netbase-1_6.1-r0 do_fetch: Failed to fetch URL http://ftp.debian.org/debian/pool/main/n/netbase/netbase_6.1.tar.xz, attempting MIRRORS if available

**Comment by persianpros** [comment]
Fetch errors are not related to Open Vision, you need to report to OE or find them via google.

For example if you search for

replex-0.1.6.8.tar.gz

you'll see it in https://ftp.fau.de/macports/distfiles/replex/
