### ISSUE TITLE
build problem 

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/openvision-development-platform#65]
ERROR: minidlna-1.2.2+gitAUTOINC+c3e3b3ff49-r0 do_configure: Execution of '/home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/temp/run.do_configure.3619' failed with exit code 2:
sed: can't read /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/git/configure.ac: No such file or directory
WARNING: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/temp/run.do_configure.3619:1 exit 2 from 'sed -i 's/AM_INIT_AUTOMAKE.*$/AM_INIT_AUTOMAKE([foreign subdir-objects])/' /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/git/configure.ac'

ERROR: Logfile of failure stored in: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/temp/log.do_configure.3619
Log data follows:
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing shell function do_configure
| sed: can't read /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/git/configure.ac: No such file or directory
| WARNING: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/temp/run.do_configure.3619:1 exit 2 from 'sed -i 's/AM_INIT_AUTOMAKE.*$/AM_INIT_AUTOMAKE([foreign subdir-objects])/' /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/git/configure.ac'
| ERROR: Execution of '/home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/temp/run.do_configure.3619' failed with exit code 2:
| sed: can't read /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/git/configure.ac: No such file or directory
| WARNING: /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/temp/run.do_configure.3619:1 exit 2 from 'sed -i 's/AM_INIT_AUTOMAKE.*$/AM_INIT_AUTOMAKE([foreign subdir-objects])/' /home/zakaria/openvision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/minidlna/1.2.2+gitAUTOINC+c3e3b3ff49-r0/git/configure.ac'
| 
ERROR: Task (/home/zakaria/openvision/openvision-development-platform/meta-openvision/recipes-connectivity/minidlna/minidlna.bb:do_configure) failed with exit code '1'

**Comment by persianpros** [comment]
Not related to us, remove your build folder and try again.

**Comment by fairbird** [comment]
@persianpros 
The problem for not full boot then image from tmp directory ... as my friend send these screenshots
/tmp dose not make symlink correctly or /var/tmp does not created 
![Screenshot from 2020-04-11 19-38-46](https://user-images.githubusercontent.com/1761779/79053855-344ade00-7c49-11ea-81a2-9d28b6d05d06.png)s,

![grab](https://user-images.githubusercontent.com/1761779/79053854-31e88400-7c49-11ea-92d9-a1742ec77ddc.png)
