### ISSUE TITLE
error ...openvision-module "ovlock"

### ISSUE THREAD

**Issue by aouamed** [OpenVisionE2/openvision-development-platform#69]
last update vuuno4kse
DEBUG: Executing shell function do_compile
NOTE: nothing to compile
/home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085: line 141: python: command not found
WARNING: /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085:141 exit 127 from 'python -O -m compileall /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0'
WARNING: Backtrace (BB generated script): 
	#1: do_compile, /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085, line 141
	#2: main, /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085, line 189
ERROR: Execution of '/home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085' failed with exit code 127:
/home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085: line 141: python: command not found
WARNING: /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085:141 exit 127 from 'python -O -m compileall /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0'
WARNING: Backtrace (BB generated script): 
	#1: do_compile, /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085, line 141
	#2: main, /home/mido/Documents/openvision-development-platform/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/ovlock/1.0-r0/temp/run.do_compile.64085, line 189

Backtrace (metadata-relative locations):
	#1: do_compile, autogenerated, line 3

**Comment by persianpros** [comment]
Try adding "python2" to https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/conf/distro/openvision-common.conf#L130 and let me know.

**Comment by aouamed** [comment]
already add:
PYTHONPATHVERSION = "python2.7"
PYTHONEXACTVERSION = "python2"
PYTHONNAMEONLY = "python"
PYTHONEXTENSION = "pyo"
and even error ...

**Comment by persianpros** [comment]
What I wrote is something else.

**Comment by aouamed** [comment]
other error ...

DEBUG: Executing shell function do_compile
NOTE: nothing to compile
/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202: line 141: python: command not found
WARNING: /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202:141 exit 127 from 'python -O -m compileall /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/plugin'
WARNING: Backtrace (BB generated script): 
	#1: do_compile, /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202, line 141
	#2: main, /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202, line 189
ERROR: Execution of '/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202' failed with exit code 127:
/home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202: line 141: python: command not found
WARNING: /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202:141 exit 127 from 'python -O -m compileall /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/plugin'
WARNING: Backtrace (BB generated script): 
	#1: do_compile, /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202, line 141
	#2: main, /home/mido/Documents/openvision-development-platform/build/tmp/work/vuuno4kse-oe-linux-gnueabi/enigma2-plugin-systemplugins-bluetoothsetup-vuuno4kse/1.0-20171114.r0/temp/run.do_compile.316202, line 189

Backtrace (metadata-relative locations):
	#1: do_compile, autogenerated, line 3

**Comment by persianpros** [comment]
Seems you OE isn't up-to-date, cd to openvision-development-platform and enter:

```
git reset --hard HEAD~10
./update.sh
```
