### ISSUE TITLE
Bug report for Open Vision | intreface eth0

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/openvision-development-platform#73]
**Open Vision revision**
OV 10.1-r150

**STB name** : vusolo

**smallflash/middleflash**
smallflash

**Describe the bug**
The problem is I have to enable the interface after every bootup otherwise it won't work,i faced this problem from my first build of the image, I don't remember what version it was.

**Comment by persianpros** [comment]
Please compile and test a new image, I want to know if https://github.com/OpenVisionE2/enigma2-openvision/commit/972786a43ac0b61e514f8dc98b2e5c5057464baa solves the problem :+1:

**Comment by ziko-ZR1** [comment]
sorry for the delay but the problem is still existing

**Comment by OpenVu** [comment]
the problem is still existing in Vu+ solo2 And Other Probleme in vfd display Vu+ solo2  he display only clock time

**Comment by persianpros** [comment]
Seems with https://github.com/OpenVisionE2/enigma2-openvision/commit/972786a43ac0b61e514f8dc98b2e5c5057464baa network is ok for now although it's not the fix and we need to find the real problem.

@OpenVu 

Please open a new issue related to your problem with logs and screenshots as we don't have such device and we can't understand the problem like that.
