### ISSUE TITLE
linux-libc-headers/linux-libc-headers_5.8.bb:do_install) failed with exit code '134'

### ISSUE THREAD

**Issue by WXbet** [OpenVisionE2/openvision-development-platform#73]
**Open Vision revision**
Tell us it's OV 10.2-r248?

**STB name**
osmini, vusolo2,dm520

**Logs**
ERROR: Task (/home/abc/OpenVisionE2/openvision-development-platform/openembedded-core/meta/recipes-kernel/linux-libc-headers/linux-libc-headers_5.8.bb:do_install) failed with exit code '134'

**Describe the bug**
Error above occurs on every build. Seems there is a lib incompatibiliy on my build system (Ubuntu 20.04.1 LTS).

Any idea?

**Comment by persianpros** [comment]
Are you using native Ubuntu like what we wrote in our README.md or WSL?

**Comment by WXbet** [comment]
I'm using it on WSL. Isn't it supported anymore? This works fine until r238.

**Comment by persianpros** [comment]
We don't know, it's not related to OV.

OE upgrades will make things harder for windows users and next update will bring pthon 3.9 and kernel 5.9 I think.

**Comment by appnostic-io** [comment]
I have Ubuntu 20.04 LTS 64-bit native as per the README and experience the same error.  Just before giving up I have:

futex(0x25f6a30, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1605282875, tv_nsec=733341000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out) 

(lots of those)

Can't see anything else of relevance unfortunately.

**Comment by dvirneuman** [comment]
@appnostic-io @WXbet Can you build any yocto image?
I'm on Ubuntu-20.04 on wsl2, and can't build yocto basic image

**Comment by WXbet** [comment]
No, its not working on WSL2 anymore. Native on Hyper-V or other VMs should work.
