### ISSUE TITLE
GigaBlue 4k display error

### ISSUE THREAD

**Issue by audi06** [OpenVisionE2/openvision-development-platform#74]
hi.
@persianpros 

Temporarily resolved the display problem with the attached file ...

`OSError: [Errno 2] No such file or directory: '/usr/share/enigma2/display'`

PS: It is taken from openatv image.
[display.zip](https://github.com/OpenVisionE2/openvision-development-platform/files/4662040/display.zip)

```
Open Vision enigma2 crash log

crashdate=Sal May 19 23:45:26 2020
compiledate=May 19 2020
skin=OctEtFHD/skin.xml
sourcedate=2020-05-19
branch=develop
rev=6a7ffa0
component=Enigma2
stbmodel=gbquad4k
stbbrand=gigablue
kernelcmdline=root=/dev/mmcblk0p5 rootwait rw rootflags=data=journal libata.force=1:3.0G,2:3.0G,3:3.0G coherent_poll=2M vmalloc=525m bmem=529m@491m bmem=608m@2464m
nimsockets=NIM Socket 0:
distro=openvision
oe=master
python=2.7.18
mediaservice=enigma2-plugin-systemplugins-servicemp3
multilib=False
architecture=cortexa15hf-neon-vfpv4
visionversion=10.1
visionrevision=r151
visionlanguage=extralanguage

**Comment by persianpros** [comment]
I think https://github.com/OpenVisionE2/meta-gigablue/commit/32653017fe85ba946790378abbaf55242690d1d8 will fix it, let me know if it's ok :+1:
