### ISSUE TITLE
SSH does not accept root's key or password

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#78]
After update to latest revision. Dropbear get's updated and since that time is impossible to log in by ssh. For lucky telnet works and I did not disabled it, so there is way how to unbrick (other than reflash).

```
Nov 15 11:50:34 sf4008 authpriv.info dropbear[2214]: Child connection from 10.0.0.5:38856
Nov 15 11:50:35 sf4008 authpriv.warn dropbear[2214]: root login rejected
Nov 15 11:50:38 sf4008 authpriv.info dropbear[2214]: Exit before auth from <10.0.0.5:38856>: (user 'root', 1 fails): Exited normally
```

```
 2212 root      2236 S    /usr/sbin/dropbear -r /etc/dropbear/dropbear_rsa_host_key -p 22 -w
```

`/usr/sbin/dropbear --help`

```
-w              Disallow root logins
```

In generic is good to disable root login over ssh/telnet and use user login then sudo. But I missing any other user for that purpose (some equvalent of "pi" use in raspberry)

Consider two fix:
1) remove -w
2) create some "openvision" user with sudo

**Comment by persianpros** [comment]
Is this because of https://github.com/OpenVisionE2/openvision-development-platform/commit/fbb91d8fdbe5985f63680238f4769ae2deb81127 ?

**Comment by petrkr** [comment]
Nope, but in that /etc/defaults/dropbear I found that extra arg `-w`

```
root@sf4008:~# cat /etc/default/dropbear 
# Disallow root logins by default
DROPBEAR_EXTRA_ARGS="-w"
root@sf4008:~# 
```

and actually this line for my sf4008 does not applies:

post install
```
root@sf4008:~# opkg install --force-reinstall dropbear
Installing dropbear (2020.81) on root
update-alternatives: removing /usr/bin/scp as no more alternatives exist for it
update-alternatives: removing /usr/bin/ssh as no more alternatives exist for it
Stopping Dropbear SSH server: stopped /usr/sbin/dropbear (pid 2249)
dropbear.
update-rc.d: /etc/init.d/dropbear exists during rc.d purge (continuing)
 Removing any system startup links for dropbear ...
  /etc/rc0.d/K10dropbear
  /etc/rc1.d/K10dropbear
  /etc/rc2.d/S10dropbear
  /etc/rc3.d/S10dropbear
  /etc/rc4.d/S10dropbear
  /etc/rc5.d/S10dropbear
  /etc/rc6.d/K10dropbear
Configuring dropbear.
update-alternatives: Linking /usr/bin/scp to /usr/sbin/dropbearmulti
update-alternatives: Linking /usr/bin/ssh to /usr/sbin/dropbearmulti
 Adding system startup for /etc/init.d/dropbear.
Starting Dropbear SSH server: Generating 2048 bit rsa key, this may take a while...
Public key portion is:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCarZ6jjwigibiMq0Es1oKQJwQ14/8v64jDMpiehII2bT7XwJ4aweABJIMmfsiyRzIM3Bir7F9D2VekaAfnJloTc2aWND+l1PB7CjYL1OnFRqwhVaS3bYSkvzR77ZmL+AGBcqF0cGSd6CY4MxIYUwjpso4WlwDmqCqpwgl26OIC8BPNoaEUqpJUdO5MOdid8DQKCPg7gM3mFSirXq+XQfa7X5nv57XpxrLdDBe8IaWq8qroy8zTfnRoPTXqNh7hSPGZJSBKxwW5YiGHT9dWLCm1ghwf6FVaERk/6vkxfdwGMfG54yV0AL5hyWEPjMHGIfgYiFNZAHTJ8BKf/Yy+g4AL root@sf4008
Fingerprint: sha1!! 1e:c8:77:aa:2a:cb:f6:59:ab:6d:88:d0:93:19:25:2c:74:f7:3d:4d
dropbear.
root@sf4008:~# cat /etc/default/dropbear 
# Disallow root logins by default
DROPBEAR_EXTRA_ARGS="-w"
root@sf4008:~# 
```

**Comment by petrkr** [comment]
Actually that file is part of dropbear package:
```
root@sf4008:/tmp# opkg files dropbear
Package dropbear (2020.81-r0) is installed on root and has the following files:
...
...
/usr/sbin/dropbearconvert
/etc/default/dropbear
...
/etc/default
```

**Comment by aouamed** [comment]
yes because of...
https://github.com/OpenVisionE2/openvision-development-platform/commit/fbb91d8fdbe5985f63680238f4769ae2deb81127

i test with I tried with the old conf
echo 'DROPBEAR_RSAKEY_ARGS="-s 1024"' >> ${IMAGE_ROOTFS}${sysconfdir}/default/dropbear

ssh work...

**Comment by petrkr** [comment]
this option will not add -w to default's config. You probably have some old config which not gets overwritten.
try force re-install package or update.

maybe on clean image with drop-bear preinstalled it will works, but consider updates as well. And key length is only about your support on client's side.

Also using 1024 key is big big security issue

**Comment by petrkr** [comment]
consider as low, because you still can use telnet.. but I am not fan of unencrypted connections at all

**Comment by 4l3x2k** [comment]
Get your .ssh/know_known right!
Remove any known fings and be happy!

**Comment by petrkr** [comment]
how can I be happy if -w deny root login ? It's not about know_host. I know how to use them. And I am sorry you think I am stupid use of windows and putty

**Comment by 4l3x2k** [comment]
I do not think so!

**Comment by 4l3x2k** [comment]
I had the same problem and removed the ip with its key from know_host and it was asking for different fingerprint.

I also think that the key generation of the target system takes some time. flash new and leave it for about 30 min.

**Comment by 4l3x2k** [comment]
-w is not present here.

**Comment by 4l3x2k** [comment]
```
root@raspberrypi3:~# cat /etc/default/dropbear 
# Disallow root logins by default
DROPBEAR_EXTRA_ARGS=""
DROPBEAR_RSAKEY_ARGS="-t ecdsa -s 521"
```

**Comment by petrkr** [comment]
> -w is not present here.

really ? So why it's in `DROPBEAR_EXTRA_ARGS="-w"`  in package ?

have you tried `opkg install --force-reinstall dropbear` ?

just because some post-script in image replace other package config is NOT right solution

**Comment by petrkr** [comment]
actually I encoure this problem, because I do not do everytime `flash new image` but do `opkg update / upgrade`

**Comment by 4l3x2k** [comment]
Because it is not recognized by bitbake.

No I did not.

That's right.

Okay. That's a packaging problem.

Doing updates is no fail!

Remove that "-w" if it is present in your image.

**Comment by petrkr** [comment]
> Remove that "-w" if it is present in your image.

I did already ... As I said I am not stupid google putty reader.


but here I will suggest this https://github.com/OpenVisionE2/openvision-development-platform/blob/fbb91d8fdbe5985f63680238f4769ae2deb81127/meta-openvision/recipes-openvision/images/openvision-image.bb#L55 move from image to that dropbear package.. because here it's done only on that images, not on package. and this is package specific thing


but talking about that

I am not fan of having root login at all... so this could be redone to have user with sudo ... but for years "easy" users are used to use enigma boxes under root and replace files on FTP/SSH under root... so .... as security guy I have no words now....

**Comment by 4l3x2k** [comment]
Well, the key is generated per device and not per package. It depends on any trophy available on that device and should be a startup script. We can't - or should not - do anything about it.

The Dropbear package is created and installed into sysroot with that options.

We're save on root! Everything else is not a "TV".

**Comment by 4l3x2k** [comment]
Sorry. Maybe I do not understand your goals.

**Comment by petrkr** [comment]
we should support updates within our images... and if someone install older image and then update.. and after that can not login, because package from OpenPLI added `-w` to options, which our package replace ONLY for tar image ,,, then it's not good.... I can uderstand if that package will stay like on debian/centos on some ".new" version but not replace running sytem

**Comment by petrkr** [comment]
It's OK . it;s low prito.

I know how to fix this on my box

So we will send `helpdesk` users to you  :)

**Comment by 4l3x2k** [comment]
You're going crazy if you try follow that ... updates.

**Comment by 4l3x2k** [comment]
Well. Kernel updates are tricky.

**Comment by petrkr** [comment]
> You're going crazy if you try follow that ... updates.
thank you for doctor's diagnose of my mind :)


but... that not excuse fact new package overwrite existing configuration and if you need make change defaults for that package, you doing that at totaly other place than that package..

and updates should work always. I am maybe crazy, but I do not want again and again reflash and again and again re-scan 4 satellites. I know i can dump lamedb, but still needs to again and again reupload/configure etc.. At my Arch Linux I also do updates and do not reinstall whole system.

Once this have package system (opkg) which supports updates, so it must work, and it working for most of the time. This is just one package, which is wrong. I found that, so I reported that. and instead 22 comments at issue it could be already fixed by moving from 1 place to right place and made config files as "conflict" so due update /etc/defaults/dropbear gets not updated but only renamed to .opkd (as happen at that kernel module last day - where it was wrong from opposite side)

**Comment by 4l3x2k** [comment]
> Get your .ssh/known_host right!
> Remove any known fings and be happy!

That was for @aouamed 

So this is a design decision for the resulting image. Do we enable root login per default? You already mentioned another user as a solution. Which is ok. It is also ok to disable root logins. 

I think that everything works as expected.

- you install image
- you use it via enigma2 and upgrade packages -> /etc/default/dropbear gets overwritten
- you telnet into the box and alter /etc/default/dropbear e.g. removing the -w and maybe reboot or restart service
- you ssh with root into the box
- you use it via enigma2 and upgrade packages -> /etc/default/dropbear gets not overwritten. instead a file with the packages contents of that file with .opkd appended is created
- now it's up to you whether you incorporate the new flags from that .opkd file

Upgrading from dropbear version older than 2 years without any modification to /etc/default/dropbear you will lock out and need to telnet.

**Comment by petrkr** [comment]
Yes thats it.

this behaviour is like red-hat based system, (which creates rpmsave suffix). For exaple debian-based systems will offer you "what to do" like
- replace file from package
- keep original
- show diff of both and let you edit

For this case is ok to NOT replace any configuration files and keep them as .opkg suffix and tell user it conflicts, so they can solve that BEFORE leave ssh session.

This is only for ssh package (you can not login back), but also for other packages, where you can lose your mount settings (in case fstab get's update) or lose enigma settings (in case enigma2.xml gets overwritten) and so on....

And if there is any update where you need replace configuration, because it is incompatible with new version, it must be wrote somewhere on "postints" message like BIG warning (which 99.9% users does not read anyway). For example gentoo does that... Redhat actually have within one release everything compatible (like you still have Apache 2.2.x so your config are compatible without whole redhat 6.x life time).

Here it is like OpenVision 10.1,, 10.2 etc... So if I update from 10.1 to 10.2, by update (not reflash) me (as user) must expect some incompatible changes, but we as releaser should not overwrite old configuration files.


About user / root login. Generaly is bad idea to login anywhere as root, but problem is, sattelite forums are full of not-linux-educated peoples who says "to work you need do chmod 777 on this text file". So if you will add them only USER account and they can not put theris "oscam.*" files to /etc/tuxbox/oscam/ because user can not write there.. then will appear suggestions like `chmod 777 /etc -r` to make that work...

So there is that opposite side, root is bad, but mostly easier for BFU... Also Enigma2 process should NOT run under root (or you saw VLC, Kodi or other media center running under root?). But that is for discussion on some discord/irc and not on Githubs issue.

For this package I just suggest do not rewrite old configuration, also do not change default configuration in "image bb", but in "dropbears bb".

**Comment by petrkr** [comment]
Ok I reflash image and SSH not working at all, it's because new generated key is ECDSA now but filename is RSA, so there is problem with it:

```
Nov 28 15:22:06 sf4008 authpriv.info dropbear[2076]: Exit before auth from <10.200.0.5:37718>: Failed assertion (../dropbear-2020.81/rsa.c:164): `key != NULL'
```
`/usr/sbin/dropbear -r /etc/dropbear/dropbear_rsa_host_key -p 22`

```
-r keyfile      Specify hostkeys (repeatable)
                defaults: 
                - dss /etc/dropbear/dropbear_dss_host_key
                - rsa /etc/dropbear/dropbear_rsa_host_key
                - ecdsa /etc/dropbear/dropbear_ecdsa_host_key
                - ed25519 /etc/dropbear/dropbear_ed25519_host_key
```

seems there is need to replace init script, as it is hard-coded there

**Comment by 4l3x2k** [comment]
What's in your /etc/dropbear/dropbear_rsa_host_key?

The first five characters are enough.

**Comment by petrkr** [comment]
```ecdsa-sha2-nistp52nistp521```

of course, since it is in `DROPBEAR_RSAKEY_ARGS="-t ecdsa -s 521"`

**Comment by petrkr** [comment]
Aha I see that now.. it must be some bug of dropbear.. If you do not clean-up `knownhosts` file, it will try to check old RSA and instead to say normal message `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED` it will crash on dropbear side.

**Comment by 4l3x2k** [comment]
What do you think or know how dropbear knows what key type is provided?

**Comment by petrkr** [comment]
> What do you think or know how dropbear knows what key type is provided?

first I suggested that from that help message it take it from default filename like `rsa` key is in `...rsa_host...` filename, as in documentation. I did not check theirs code. But now had more testing with replace init.d etc and found it's not due that.

maybe can put somewhere to documentation something like

"If you encoure error during ssh connect like client side: `ssh <IP> connection reset` and on STB log is `Failed assertion..` then remove remote host from `.known_hosts`"

**Comment by 4l3x2k** [comment]
I already added documentation tag to this issue. I do not know whether it is possible to jump to specific comment?! 
Now you encounter the same problem as aouamed.

Without viewing dropbears code or doc I see that the type of key being used is not related to the name of the key file. Type of key is in that key file.
The help message say, that if you do not supply -r, some default paths are walked. nothing more. otherwise you would need to supply the type of key via another switch or something like -r rsa:name_of_file. but that is not the case.
