### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by audi06** [OpenVisionE2/openvision-development-platform#80]
Hi,
stbmodel=dm900
stbbrand=dreambox
distro=openvision
visionversion=10.1
visionrevision=r158
```
<  4786.8442> 01:51:58.2506 Traceback (most recent call last):
<  4786.8443> 01:51:58.2507   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 59, in action
<  4786.8446> 01:51:58.2509   File "/usr/lib/enigma2/python/Screens/Ci.py", line 490, in okbuttonClick
<  4786.8449> 01:51:58.2512 IndexError: tuple index out of range

**Comment by persianpros** [comment]
Please don't remove sections from the crashlogs, sometimes we need all the log or even a full dmesg to understand what's happening.

**Comment by audi06** [comment]
**Method 1**
"CI Operation Mode" Press OK button after making selection, device is locked.
[enigma2_crash_2020-05-30_16-42-05.log](https://github.com/OpenVisionE2/openvision-development-platform/files/4705712/enigma2_crash_2020-05-30_16-42-05.log)


**Method 2**
`init 4&& sleep 5&& ENIGMA_DEBUG_LVL=4 enigma2`
```
<   876.4782> 16:50:11.2384 [ActionMap] Keymap 'OkCancelActions' -> Action = 'ok'.
<   876.4784> 16:50:11.2386 Traceback (most recent call last):
<   876.4785> 16:50:11.2386   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 59, in action
<   876.4787> 16:50:11.2389   File "/usr/lib/enigma2/python/Screens/Ci.py", line 490, in okbuttonClick
<   876.4789> 16:50:11.2391 IndexError: tuple index out of range
<   876.4790> 16:50:11.2392 [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0xadf0f5f8>>,('OkCancelActions', 'ok')) failed)
<   880.4734> 16:50:15.2335 [gRC] main thread is non-idle! display spinner!
Killed

**Comment by norhap** [comment]
@audi06 test please
https://forum.openvision.tech/viewtopic.php?f=12&t=293&p=9425#p9425

**Comment by audi06** [comment]
@norhap 
Hi my friend.
I tested it on dm900 device it is working fine. I will report to you after testing on other model devices. I started getting feedback from users.

**Comment by norhap** [comment]
Done:
https://github.com/OpenVisionE2/enigma2-openvision/commit/073b5ad560ebfa1e3749eb1df72d9e50594adfff
