### ISSUE TITLE
Vision module: The new generation

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/openvision-development-platform#88]
https://github.com/OpenVisionE2/openvision-development-platform/commit/a470ecbd49623a7fa99ad2887f34d463e9f52b19

Public git: https://github.com/OpenVisionE2/openvision-module

I think we need to make it compatible for old kernels like

4.x (may be 100% compatible just now)
3.x
2.x

As I just tested this module with kernel 5.x so feel free to help me with this.

Now if you

`cd /proc/openvision/`

You'll see our proc files which could be used instead of /etc/openvision/ path.

Reference for old kernels: https://github.com/OpenVisionE2/sh4-driver/blob/master/e2_proc/e2_proc_main.c

**Comment by petrkr** [comment]
`Linux sf8008 4.4.35 #1 SMP Tue Oct 8 08:52:53 UTC 2019 armv7l GNU/Linux`

```
root@sf8008:~# for i in $(ls /proc/openvision/); do echo "$i"; echo -ne "  "; cat /proc/openvision/$i; done  
architecture
  cortexa15hf-neon-vfpv4
blindscanbinary
  octagon-blindscan
brand
  octagon
developername
  petrkr
distro
  openvision
feedsurl
  http://openvision.yacp.net/feeds/openvision-develop
forcemode
  no
imagedir
  octagon/sf8008
imagefs
   octagonemmc
kernel
  4.4.35
kernelfile
  kernel.bin
mediaservice
  enigma2-plugin-systemplugins-servicehisilicon
middleflash
  False
mkubifs
  
model
  sf8008
mtdbootfs
  
mtdkernel
  mmcblk0p12
mtdrootfs
  mmcblk0p16
multilib
  False
oe
  master
platform
  octagonhisil
python
  2.7.18
rcidnum
  2
rcname
  sf8008
rctype
  0
rootfile
  rootfs.tar.bz2
smallflash
  False
socfamily
  hisi3798mv200
ubinize
  
visionlanguage
  extralanguage
visionrevision
  r280
visionversion
  10.2
```

**Comment by persianpros** [comment]
Seems all models/brands are ok except dm800 with kernel 2.6.18:

https://github.com/OpenVisionE2/openvision-module/blob/master/source/openvision/openvision_procfs_main.c#L77 won't work for kernel < 2.6.26 as it says too few arguments.

**Comment by 4l3x2k** [comment]
Yep. The call to d_path requires four arguments. The comparison is based on the following

master
https://github.com/torvalds/linux/blob/7059c2c00a2196865c2139083cbef47cd18109b6/fs/d_path.c#L246
https://github.com/torvalds/linux/blob/7059c2c00a2196865c2139083cbef47cd18109b6/include/linux/fs.h#L916

2.6.18
https://github.com/torvalds/linux/blob/e478bec0ba0a83a48a0f6982934b6de079e7e6b3/fs/dcache.c#L1473
https://github.com/torvalds/linux/blob/e478bec0ba0a83a48a0f6982934b6de079e7e6b3/include/linux/fs.h#L671

linux/fs/d_path.c:d_path -> linux/fs/dcache.c:d_path

The call could be made conditional on KERNEL_VERSION and should look like this:
`ptr = d_path(file->f_dentry, file->f_vfsmnt, path, PAGE_SIZE);`

**Comment by persianpros** [comment]
Ok dm800 is ok now and we can close this as all brands/models could compile the new module :+1:

**Comment by persianpros** [comment]
@petrkr 

Would you please compile for "h7" with feeds on your server?

Ian is working with us and soon so many improvements will be added to OV but he needs to test everything in OV so a test image without feeds won't do the job.

Thanks in advance :+1:

**Comment by petrkr** [comment]
Uploaded http://openvision.yacp.net/images/h7/

**Comment by persianpros** [comment]
@petrkr 

Can you update it? Current image won't boot on h7 but last one does so I want to be sure if https://github.com/OpenVisionE2/meta-zgemma/commit/b50218a9be82671efdbe67cabe083965e5e74663 is the fix ...

**Comment by petrkr** [comment]
My build env gets broken see #93 I will try clean build (with original backup)

**Comment by petrkr** [comment]
ok removed build seems fixed that (for now). But h7 can not compile because of:

```
cp: cannot stat '/home/builder/openvision-development-platform/build/tmp/work/h7-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/deploy-openvision-enigma2-image-image-complete/openvision-enigma2-develop-extralanguage-python2-10.2-r293-h7.rootfs.tar': No such file or directory
```

hmm so on 2nd run it passed.

**Comment by petrkr** [comment]
uploaded

**Comment by persianpros** [comment]
@petrkr 

If it's possbile for you please update all your builds to r296 and check if the time is ok or not.

**Comment by petrkr** [comment]
after update it is ok... But whenever I will have mood to set-up and rescan whole astras.. Maybe could be good to do openmultiboot with version (r) too, I do not know from what is that name generaterd, but all images are only like "openvision-development" without -rxxx suffix.

**Comment by persianpros** [comment]
@petrkr 

You could check https://github.com/OpenVisionE2/openmultibootmanager and https://github.com/OpenVisionE2/openmultiboot sources :+1:

**Comment by persianpros** [comment]
@petrkr 

Please update the "h7" build so Ian could work with the new python-pytz from our feeds.

Thanks in advance :+1:

**Comment by petrkr** [comment]
Forgot upload it, nevermind, I will recompile latest master now and upload that..

**Comment by petrkr** [comment]
@persianpros uploaded http://openvision.yacp.net/images/h7/
