### ISSUE TITLE
Image build fails for Open Vision 10.1 r164 for Azbox HD

### ISSUE THREAD

**Issue by vk2amv** [OpenVisionE2/openvision-development-platform#9]
**Open Vision revision**
Open Vision 10.1 r164 (Build also failed on r158 with same error)

**STB name**
azboxhd

**Logs**
Logs attached in zip file
[Openvision_build_logs_azboxhd.zip](https://github.com/OpenVisionE2/openvision-development-platform/files/4758905/Openvision_build_logs_azboxhd.zip)

Zip file has a log of full console output from starting image.sh script to failure of the build

Also has the full contents of build log directory
openvision-development-platform/build/tmp/work/azboxhd-oe-linux/linux-azbox/3.9.2-openvision/temp/

**Describe the bug**
Build for azboxhd fails when trying to build Specific, Vision image.
Build errors out with gcc: error: unrecognized command line option

**To Reproduce**
Fresh install of Ubuntu 18.04.4 x64 LTS Desktop
(Tried inside both VMWare and Hyper-V Server)
Make sure Ubuntu is fully up to date with apt-get.

Cloned openvision-development-platform as per instructions in README.md

Executed image.sh script.

Select Specific build, Vision, and azboxhd machine.

Wait for build to fail.

I have NOT tried the Feeds build yet for azboxhd.

**Expected behavior**
Build to complete and produce an image for the azboxhd.

Note that this build works sucessfully when building mbmini Vision and Feeds.
I built the mbmini image and it is working perfectly fine on two boxes using that mbmini image.

**Screenshots**
Console logs and build log files attached

**Comment by kueken** [comment]
https://github.com/openembedded/openembedded-core/commit/0851e03daebeeb7e0579baa3aa195c228652d97b
Could come from Openssl Patch.
Maybe you try building without the patch?

**Comment by persianpros** [comment]
Did you try our "ltsubuntu.sh"?

Seems you have missing tools ...

**Comment by persianpros** [comment]
Confirmed, seems new GCC updates in OE made this problem.

I'm investigating it: https://forum.openvision.tech/viewtopic.php?f=6&p=9950

**Comment by persianpros** [comment]
https://github.com/OpenVisionE2/openvision-development-platform/commit/ab799158188b8b20c77ac7ee9d8d906d810e2754 will fix it, just run ltsubntu.sh again after getting the new git updates:

cd openvision-development-platform
git pull
image.sh or ltsubuntu.sh
