### ISSUE TITLE
ERROR: octagon-dvb-modules-sf8008-4.4.35+20201207-r0 do_fetch

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#92]
`Sstate summary: Wanted 1693 Found 25 Missed 1668 Current 698 (1% match, 30% complete)
NOTE: Executing Tasks
WARNING: octagon-dvb-modules-sf8008-4.4.35+20201207-r0 do_fetch: Failed to fetch URL http://source.mynonpublic.com/octagon/sf8008-hiko-20201207.zip, attempting MIRRORS if available
ERROR: octagon-dvb-modules-sf8008-4.4.35+20201207-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1323"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/atef/openvision-development-platform/openembedded-core/scripts:/home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/recipe-sysroot/usr/bin/crossscripts:/home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/recipe-sysroot-native/usr/sbin:/home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/recipe-sysroot-native/usr/bin:/home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/recipe-sysroot-native/sbin:/home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/recipe-sysroot-native/bin:/home/atef/openvision-development-platform/bitbake/bin:/home/atef/openvision-development-platform/build/tmp/hosttools"; export HOME="/home/atef"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/atef/openvision-development-platform/sources 'http://source.mynonpublic.com/octagon/sf8008-hiko-20201207.zip' --progress=dot -v failed with exit code 8, output:
--2020-12-10 16:54:31--  http://source.mynonpublic.com/octagon/sf8008-hiko-20201207.zip
Resolving source.mynonpublic.com (source.mynonpublic.com)... 176.9.45.237
Connecting to source.mynonpublic.com (source.mynonpublic.com)|176.9.45.237|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-10 16:54:31 ERROR 404: Not Found.

ERROR: octagon-dvb-modules-sf8008-4.4.35+20201207-r0 do_fetch: Fetcher failure for URL: 'http://source.mynonpublic.com/octagon/sf8008-hiko-20201207.zip'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/atef/openvision-development-platform/build/tmp/work/sf8008-oe-linux-gnueabi/octagon-dvb-modules-sf8008/4.4.35+20201207-r0/temp/log.do_fetch.71802
ERROR: Task (/home/atef/openvision-development-platform/meta-octagon/recipes-bsp/drivers/octagon-dvb-modules-sf8008.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2823 tasks of which 2426 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-octagon/recipes-bsp/drivers/octagon-dvb-modules-sf8008.bb:do_fetch
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:100: image] Error 1
atef@atef-ganm:~/openvision-development-platform$ 
`

**Comment by persianpros** [comment]
Fxied :+1:
