### ISSUE TITLE
build error pseudo

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#93]
FileNotFoundError: [Errno 2] No such file or directory: '/home/builder/openvision-development-platform/build/tmp/sysroots-components/x86_64/pseudo-native/usr/bin/pseudo'

actually also h7 after build h7

**Comment by persianpros** [comment]
@petrkr 

Would you please update h7 build so IanSav could work with latest updates/feeds?

He's adding new changes to our enigma2 only and needs updated image at least once a week.

If it's possible for you please help us with this matter :+1:

**Comment by petrkr** [comment]
Uploaded https://openvision.yacp.net/images/h7/
