### ISSUE TITLE
glibc-2.25-r0 do_package: Error executing a python function in exec_python_func 

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#94]
Sstate summary: Wanted 3289 Found 398 Missed 2891 Current 1536 (12% match, 40% complete)
NOTE: Executing Tasks
ERROR: glibc-2.25-r0 do_package: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:perform_packagecopy(d)
     0003:
File: '/home/atef/openvision-development-platform/openembedded-core/meta/classes/package.bbclass', lineno: 826, function: perform_packagecopy
     0822:        rpath_replace (dvar, d)
     0823:}
     0824:perform_packagecopy[cleandirs] = "${PKGD}"
     0825:perform_packagecopy[dirs] = "${PKGD}"
 *** 0826:
     0827:# We generate a master list of directories to process, we start by
     0828:# seeding this list with reasonable defaults, then load from
     0829:# the fs-perms.txt files
     0830:python fixup_perms () {
File: '/usr/lib/python3.8/subprocess.py', lineno: 411, function: check_output
     0407:        # Explicitly passing input=None was previously equivalent to passing an
     0408:        # empty string. That is maintained here for backwards compatibility.
     0409:        kwargs['input'] = '' if kwargs.get('universal_newlines', False) else b''
     0410:
 *** 0411:    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
     0412:               **kwargs).stdout
     0413:
     0414:
     0415:class CompletedProcess(object):
File: '/usr/lib/python3.8/subprocess.py', lineno: 512, function: run
     0508:            # We don't call process.wait() as .__exit__ does that for us.
     0509:            raise
     0510:        retcode = process.poll()
     0511:        if check and retcode:
 *** 0512:            raise CalledProcessError(retcode, process.args,
     0513:                                     output=stdout, stderr=stderr)
     0514:    return CompletedProcess(process.args, retcode, stdout, stderr)
     0515:
     0516:
Exception: subprocess.CalledProcessError: Command 'tar -cf - -C /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/glibc/2.25-r0/image -p -S . | tar -xf - -C /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/glibc/2.25-r0/package' returned non-zero exit status 134.

Subprocess output:
abort()ing pseudo client by server request. See https://wiki.yoctoproject.org/wiki/Pseudo_Abort for more details on this.
Check logfile: /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/glibc/2.25-r0/pseudo//pseudo.log
/bin/sh: line 1: 1396794 Broken pipe             tar -cf - -C /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/glibc/2.25-r0/image -p -S .
     1396795 Aborted                 (core dumped) | tar -xf - -C /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/glibc/2.25-r0/package

ERROR: Logfile of failure stored in: /home/atef/openvision-development-platform/build/tmp/work/sh4-oe-linux/glibc/2.25-r0/temp/log.do_package.1396726
ERROR: Task (/home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc_2.25.bb:do_package) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6420 tasks of which 4526 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc_2.25.bb:do_package
Summary: There were 5 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:104: feed] Error 1

Done, the compiled image is in build/tmp/deploy/images/spark folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r293-spark.zip
atef@atef-ganm:~/openvision-development-platform$

**Comment by persianpros** [comment]
Use cleanup.sh
