### ISSUE TITLE
OSCam: Irdeto Layer 2B

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#96]
There are few new channels which uses new irdeto layer 2b format. There are some private images (ex. OpenPLI for Qviart boxes) where is some "private" working oscam.

Will be good if OpenVision image can decode those channels too. Without this support every E2 box without this support will be useless for this provider

Could be good to have that open source as OSCam is under GPL3 licence so every changes made to oscam must be provided with binary.

**Comment by persianpros** [comment]
Maybe they're using oscam-emu not pure oscam but if that's a closed-source cam then we can't include it.
